### ISSUE TITLE
Connection issues. Retrying...

### ISSUE THREAD

**Issue by sredlin** [5andr0/PogoLocationFeeder#102]
PogoLocationFeeder is brought to you via https://github.com/5andr0/PogoLocationFeeder/wiki
This software is 100% free and open-source.

Connecting to feeder service pogo-feed.mmoex.com
Connection issues. Retrying...
Connection established. Waiting for data...
Connection issues. Retrying...
Pokesnipers API down: Der Remoteserver hat einen Fehler zurückgegeben: (503) Server nicht verfügbar.
Server: PokemonGo Rare Hunting, Channel: rare_pokemon ID: Victreebel, Lat:25,3318425676275, Lng:55,3622020801097, IV:0
Pokesnipers API down: Der Remoteserver hat einen Fehler zurückgegeben: (503) Server nicht verfügbar.
Server: PokéGO- Chat, rare spots!, Channel: rare_spotting ID: Missingno, Lat:-33,867333, Lng:151,1939894, IV:0
Pokesnipers API down: Der Remoteserver hat einen Fehler zurückgegeben: (503) Server nicht verfügbar.
Server: PokemonGo Rare Hunting, Channel: rare_pokemon ID: Machamp, Lat:-33,874968, Lng:151,218668, IV:0
Pokesnipers API down: Der Remoteserver hat einen Fehler zurückgegeben: (503) Server nicht verfügbar.
Server: PokemonGo Rare Hunting, Channel: rare_pokemon ID: Charizard, Lat:48,024086, Lng:-1,745365, IV:0
Experiencing connection issues. Throttling...

are the servers down? or does i have to change some settings for first use?

**Comment by MrCosgrove1** [comment]
Same here

**Comment by jgwallace3** [comment]
It also seems to try to connect to pokesnipers despite setting config entry to false.

**Comment by Ilses** [comment]
Hi -- Can you all try the latest release? I believe the pokesnipers integration has broken (new Cloudflare DDoS protection), but setting the config to false should work in v0.1.2
