### ISSUE TITLE
Costura.Fody.2.0.0-beta0018

### ISSUE THREAD

**Issue by Brumotti** [5andr0/PogoLocationFeeder#105]
please tell me why visual studio shows this error:

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Costura.Fody.2.0.0-beta0018\build\Costura.Fody.targets.	PogoLocationFeeder	\PogoLocationFeeder-master\PogoLocationFeeder\PogoLocationFeeder.csproj	158

**Comment by yps** [comment]
Just do what it tells you to... Install the Nuget packages

**Comment by Ilses** [comment]
Odd... are you building from master, or from the v1.2  .zip / .tar.gz ?

**Comment by Ilses** [comment]
I'm not sure what could be causing this aside from visual studio being silly. Could you try cloning the repo again on the latest master?
