### ISSUE TITLE
A lot of UNKNOWN_SOURCE

### ISSUE THREAD

**Issue by mrjihai** [5andr0/PogoLocationFeeder#107]
There is a lot of UNKNOWN_SOURCE appeared. I hope the bot only listen to the discord. But it seems to listen from sources other than discord.  I  try to  put   "usePokeSnipers": false,  "useTrackemon": false. The situation is still the same.

**Comment by CTCal** [comment]
Yesh. I removed all but the 90+IV channels and set the other services to "false" yet only get "UNKNOWNSOURCE" stuff with crap IVs.

**Comment by bebar69** [comment]
![image](https://cloud.githubusercontent.com/assets/20604340/17337559/7bf1b6e4-58e3-11e6-8fdc-36cb7aded23f.png)
Lastest version, try master version Too

**Comment by Rabelaiss** [comment]
I dont get it, what is supposed to be this unknown source ?

**Comment by Ilses** [comment]
I've updated the wiki with information on UNKNOWN_SOURCE.

**Comment by CTCal** [comment]
So in other words, by changing discord_channels.json we are just removing the ID of the source? Not stopping it from fetching from that source?

Really needs an option for filtering by source or IV/pokemon. At least if it's going to spam this many unknown/low IV or useless pokes with no option to stop it. Ignoring in Necro means you also ignore regular pokemon which I want for leveling.

**Comment by Ilses** [comment]
Yep -- for now, you can use client-side options to snipe only desired pokemon (pokemon to snipe list, desired iv). We will be working toward either updating Necro's handling of unknown IV pokemon or allowing for server-side pokemon prioritization, channel enable/disable, etc.

**Comment by bebar69** [comment]
Why remove channel feature?
