### ISSUE TITLE
Token Bot to join channel

### ISSUE THREAD

**Issue by AbuGosok** [5andr0/PogoLocationFeeder#11]
Hi,

I made token using https://discordapp.com/developers/applications/me but it does not feed to any channel. If I use normal authentication, it feeds just fine because I already join the invite.

I guess the bot needs to join:
    "sniping",
    "high_iv_pokemon",
    "rare_pokemon"

The question is, how to make bot join the channel?

**Comment by Ilses** [comment]
You have to ask a server mod to invite the bot to a server. Creating a bot should have given you an invite link for doing so.

That said, it's much easier to use discord user/pass and I would highly recommend doing so.
