### ISSUE TITLE
log4net:ERROR

### ISSUE THREAD

**Issue by kalianleung** [5andr0/PogoLocationFeeder#110]
log4net:ERROR Failed to find configuration section 'log4net' in the application's .config file. Check your .config file for the <log4net> and <configSections> elements. The configuration section should look like: <section name="lo
g4net" type="log4net.Config.Log4NetConfigurationSectionHandler,log4net" />
PogoLocationFeeder is brought to you via https://github.com/5andr0/PogoLocationFeeder
This software is 100% free and open-source.

**Comment by mcc4ll** [comment]
I've got the same problem.

**Comment by thaloco1983** [comment]
Same error with the CLI.

With GUI, i'm being able to retrieve results. But most of the results will expiry quickly.

**Comment by djdookie** [comment]
same. you should test the releases beforehand guys. ;)

**Comment by forReason** [comment]
compile the repository your self or use my compiled version
https://github.com/5andr0/PogoLocationFeeder/files/398236/sniperuuu.zip

**Comment by Ilses** [comment]
I believe this is fixed as of 0.1.3, and we just pushed 0.1.4. Can you try the latest release, and re-open this issue if the problem persists?

Thanks!
