### ISSUE TITLE
Unknown_Source

### ISSUE THREAD

**Issue by bebar69** [5andr0/PogoLocationFeeder#113]
I'am on lastest version and i have try master version too
Channels is not news : it's on default config just remove all other exept this one

Take minute for look screenshot

**On location Feeder GUI Snorlax... NOT send ON CHANNEL 100_iv**

![image](https://cloud.githubusercontent.com/assets/20604340/17337970/819893b8-58e5-11e6-993f-cc092f742169.png)

discord_channels.json
[ 
{
"id": "209314800935763977",
"Server": "Necrobot.io",
"Name": "100_iv"
}
]

**Comment by Jacosci** [comment]
https://github.com/5andr0/PogoLocationFeeder/wiki/Configuration-and-Usage

Give that a read.

**Comment by CTCal** [comment]
Really, great stuff. But if you add an internal ignore filter (IV/CP/Pokename) it would be smashing.

**Comment by luumanhvn** [comment]
damn it this Unknown_Source

**Comment by Ilses** [comment]
The new 0.1.4 release allows you to ignore channels by removing them from your discord_channels.json. Since that seemed to be what the OP was trying to do, I'm closing this issue.
