### ISSUE TITLE
Pogolocationfeeder says im missing something any help?

### ISSUE THREAD

**Issue by venenata** [5andr0/PogoLocationFeeder#114]
![image](https://cloud.githubusercontent.com/assets/20799950/17338367/2d88fb58-58b5-11e6-8fe1-52a54f83341b.png)

**Comment by forReason** [comment]
compile the repository with visualstudio or use my compiled version:
https://github.com/5andr0/PogoLocationFeeder/files/398236/sniperuuu.zip (latest build)

**Comment by Ilses** [comment]
log4net dependencies should be fixed as 0.1.3. Could you try out the latest v0.1.4 release, and re-open this issue if the problem persists?

Thanks!
