### ISSUE TITLE
master branch is broken

### ISSUE THREAD

**Issue by vdepagter** [5andr0/PogoLocationFeeder#116]
Can't compile master branch anymore! What a mess :')

![image](https://cloud.githubusercontent.com/assets/7669336/17338943/ec3a7674-58e9-11e6-891f-bb101c5d720e.png)

**Comment by d3structor84** [comment]
Confirmed.

Release-CLI version isnt working too.

**Comment by incizzle** [comment]
same here :(

**Comment by GhostlyCrowd** [comment]
Can confirm.

**Comment by d3structor84** [comment]
I think #54 broke the master.
Missing file was renamed as it seems.

**Comment by mt247** [comment]
Yes I have also this problem

**Comment by francastro** [comment]
+1 here

**Comment by Roxazlp** [comment]
Ilses is working on it. Use the GUI-Version until fixed master branch and cli release.

**Comment by dogramacigokhan** [comment]
Can confirm. Missing files, renamed but not refactored classes and missing declerations. The branch is broken.

**Comment by yps** [comment]
Just use the GUI-Version till it's fixed

**Comment by dogramacigokhan** [comment]
GUI version has memory leaks according to the wiki page.

**Comment by tensei** [comment]
fix inc.

**Comment by Ilses** [comment]
Just getting around to issues again -- the master branch should be stable again. Sorry about the dev leakage!

**Comment by vdepagter** [comment]
@Ilses Thanks for your work!
