### ISSUE TITLE
log4net?

### ISSUE THREAD

**Issue by SeaPotatos** [5andr0/PogoLocationFeeder#117]
log4net:ERROR Failed to find configuration section 'log4net' in the application's .config file. Check your .config file for the <log4net> and <configSections> elements. The configuration section should look like: <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,log4net" />

**Comment by mochdev** [comment]
yeah me too

**Comment by leandrolsf** [comment]
me too

**Comment by mhvuze** [comment]
Same here in CLI.

**Comment by oxsi91** [comment]
for now the solution only use the GUI until they update it.

**Comment by forReason** [comment]
compile the repository with visualstudio or use my compiled version:
https://github.com/5andr0/PogoLocationFeeder/files/398236/sniperuuu.zip (latest build)

**Comment by Ilses** [comment]
I believe this was fixed as of 0.1.3, and we just pushed 0.1.4. Could you try our latest release, and re-open this issue if the problem persists?

Thanks!
