### ISSUE TITLE
why missingno read in necrobot as scanning for snipeable pokemon without name

### ISSUE THREAD

**Issue by pokessan** [5andr0/PogoLocationFeeder#118]
in pogolocationfeeder app shows there is missingno pokemon in the coord, but necrobot shows scanning for snipeable pokemon, and no missingno pokemon ever catch 
what is the problem ? thanks :)

**Comment by GhostlyCrowd** [comment]
Misingno is the feeders way of displaying a pokemon of which its name cannot be parsed. 


Misingno is not in the game.

**Comment by pokessan** [comment]
oo,,, I see,,thanks GhostlyCrowd :) I saw there is mew, only snipping mew,,, but no try to catch it (as like skip it away) once I have met mew show the info in pogolocationfeeder mew with IV:18 only so its automatically throw with basic pokeball only,,, and fleeaway,, :(

**Comment by GhostlyCrowd** [comment]
Mew is not obtainable in the game yet, Every time you see Mew its a troll feeding fake data to one of the discord channels

**Comment by yps** [comment]
There is no mew in the game yet.

**Comment by Ilses** [comment]
Cool -- looks like this is answered, so I will close the issue
