### ISSUE TITLE
Missing file "PokeSniperReader.cs" in Master

### ISSUE THREAD

**Issue by weedorbeat** [5andr0/PogoLocationFeeder#120]
The "PokeSniperReader.cs" file is missing. Was referenced by the following changes in commit #108

**Comment by d3structor84** [comment]
master-branch is broken atm

**Comment by weedorbeat** [comment]
I know I've run into on locally. But only by commenting out the missing class.

**Comment by Ilses** [comment]
Master should be fixed again -- sorry about that!
