### ISSUE TITLE
Disable channels?

### ISSUE THREAD

**Issue by mhvuze** [5andr0/PogoLocationFeeder#123]
Hey,

I wonder if it's already possible to disable certain channels or if not, if this is a planned feature? 

For example I only want to receive coordinates from the 90/100iv channels in the config. Deleting the entries in discord_channels.json only removes the matching server names but the feed still lists coordinates from the other rooms.

Best regards.

**Comment by GhostlyCrowd** [comment]
config > discord_channels.json

Remove what you dont want in there

**Comment by ItzBlackStar** [comment]
This isnt true, the discord_channels.json is to help the program tell you were the pokemon shown are from. They have nothing to do with controling what servers it farms.

Removing servers will just make the program display some pokemon sources Unknown_Source

**Comment by MournRAGE** [comment]
I really want to customize what channels to receive coordinates from as well. As it stands the feeder is pulling every set of coordinates it gets and my bot is downright spammed with pokemon I do not want or need; wasting a lot of time and a lot of pokeballs.

**Comment by Ilses** [comment]
Hey -- we'll try to allow you to enable / disable channels once more in the future. In the meantime, please configure your client settings (NecroBot/MobBot) to set which pokemon you wish to catch and your desired IV threshold.

**Comment by mhvuze** [comment]
Did you even bother to read the OP, GhostlyCrowd...

I appreciate it Ilses! I've already setup my bot appropiately but most coordinate sets just don't come with an IV value, so just pulling everything from the dedicated 90/100 channels (despite not being 100% reliable either) would be great.

**Comment by vdepagter** [comment]
Seconded, really expect it to work that way (not listed in discord_channels.json == ignore it!!)

**Comment by Ilses** [comment]
Yeah -- sorry about the downgrade to channel selection. We're also looking into solutions to increase the reliability of feed data (crowdsourcing, or a even a simple bot that visits feed locations, then and emits a cleaned and accurate feed). In the short term, we might just make a config option for a list of channels to ignore.

**Comment by dody19852002** [comment]
i suggest, 2 channels max each server approved... there too much rare channel posting the same coord...for our sake

**Comment by Ilses** [comment]
The defaults will err toward being inclusive of new channels. We just released 0.1.4, which allows you to ignore channels by removing them from your discord_channels.json!
