### ISSUE TITLE
Error on pogo launch

### ISSUE THREAD

**Issue by Fullatx** [5andr0/PogoLocationFeeder#127]
Hey, first thx for your work, i got this error on launch , im running it under windows 10 x64
![sans titre](https://cloud.githubusercontent.com/assets/15093639/17344209/9f918318-5901-11e6-9999-f74f29027320.png)

**Comment by Ilses** [comment]
Just a quick clarification -- are you working from release v1.0.2, or from master branch?

**Comment by forReason** [comment]
from the release. same here. the gui release works just fine

**Comment by Fullatx** [comment]
from the last release

**Comment by Ilses** [comment]
Hey -- I believe this is fixed as of 0.1.3, and we just pushed 0.1.4. Can you try the latest release, and re-open this if the issue persists?

Thanks!
