### ISSUE TITLE
CLI Version doesn't show Pokemon anymore

### ISSUE THREAD

**Issue by MisterFab1an** [5andr0/PogoLocationFeeder#130]
In the latest version, the CLIE client doesn't show any pokemon in the command window. However, the data from the discord channels still get transfered to the bot client.

(You can see the pokemon in the GUI client)

**Comment by Ilses** [comment]
When you say you aren't seeing any pokemon, does that mean see 'Missingno' entries, or nothing is displaying at all? Can you post your logs or an image?

**Comment by forReason** [comment]
nothing displayed at all with a errormessage:
 lol4net:ERROR failed to find configuration sectin 'log4net' in the application's config file. Check your .config file for the <log4net> and <configsectons> elements. The configuration section should look like. <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,lognet" />

**Comment by forReason** [comment]
below "pogolocationfeeder is brought to you by...
this software is 100% open source..."

**Comment by d4rklord** [comment]
Getting this error when I run CLI version

log4net:ERROR Failed to find configuration section 'log4net' in the application's .config file. Check your .config file for the <log4net> and <configSections> elements. The configuration section should look like: <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,log4net" />

Looking through the config, nothing mentions log4net at all.

**Comment by Dewamade** [comment]
https://github.com/5andr0/PogoLocationFeeder/issues/146#issuecomment-237210291

**Comment by Ilses** [comment]
I believe this should be fixed in 0.1.3, and we just pushed 0.1.4. Could you try one of these versions, and re-open this issue if the problem persists?

Thanks!
