### ISSUE TITLE
is there a way to copy Cords only in Gui

### ISSUE THREAD

**Issue by ladymPokeD** [5andr0/PogoLocationFeeder#132]
I try to copy the cords only;however, it copied the entire line.

Please advise?

**Comment by tensei** [comment]
added a copy button 
output is =>  lat, lng

**Comment by ExcuseMi** [comment]
@tensei http://pokesnipers.com/ uses a link to open pokesnipers and snipe it, could we add that?
Example link: pokesniper2://Lapras/22.2872151683,114.131440798

**Comment by tensei** [comment]
@ExcuseMi done

**Comment by ladymPokeD** [comment]
Awesome. Thank you.
