### ISSUE TITLE
Ignored Sniped pokemon

### ISSUE THREAD

**Issue by catsandcodes** [5andr0/PogoLocationFeeder#136]
So Necrobot is ignoring some of the pokemons apearing in the feeder, any ideas what might be causing this. Like it gets some of the once appearing but some are being ignored and just displays 

ex: (SNIPER) Sniping a Chansey with unknow IV at 12.3456789, -12.3456789

but it never tries to capture it.

**Comment by kthejoker20** [comment]
working fine for me, your config file must be wrong.  BTW... go to necrobot site if you have issues with it.

**Comment by catsandcodes** [comment]
sorry about that, ive heard sometimes people post a fake snipe so any idea if that could be it.
