### ISSUE TITLE
Pokesnipers not working anymore

### ISSUE THREAD

**Issue by djdookie** [5andr0/PogoLocationFeeder#139]
Although there are new entries on pokesnipers.com, PogoLocationFeeder doesst receive them anymore.
My current build is at 91abca54.

**Comment by Nipper4369** [comment]
try restarting the program. There is a issue if it running it some times will stop using all feed loactions but trackemon

**Comment by djdookie** [comment]
I tried restarting several times, which didn't help.
Currently I get a lot of discord coords and a few trackemon coords, but still no pokesniper coords.

**Comment by Nipper4369** [comment]
Now that I look at it you are right it no longer grabs pokesniper even if set to true.

**Comment by djdookie** [comment]
Glad I'm not the only one! ;)

**Comment by Ilses** [comment]
I've got this mentioned on the wiki, so will be closing for now as a known bug.

**Comment by djdookie** [comment]
I think cloudflare is preventing the bot's requests now.
