### ISSUE TITLE
monitoring more than 1 channel

### ISSUE THREAD

**Issue by Marsinator** [5andr0/PogoLocationFeeder#14]
It seems finds pop in faster than the bot can handle, sometimes jumping over finds, say we find 10, bot "only" snipes 1, 5 and 10.

is this an issue?

**Comment by skupfer** [comment]
This is NOT a PogoLocationFeeder related issue. God. The Feeder is working properly.

Related to NecroBot and it's config. You could try to lower the delay between snipes, maybe this helps.

**Comment by Ilses** [comment]
Yep, NecroBot only snipes when it's not busy with other tasks (spinning pokestops, catching nearby pokemon, etc). Take a look at the `MinDelayBetweenSnipes` variable. You can also fiddle with NecroBot's other delays.
