### ISSUE TITLE
Can't edit channels

### ISSUE THREAD

**Issue by daidaisfa** [5andr0/PogoLocationFeeder#142]
it won't effect after i edit the channel file. Hope you can add this channel in your next release:
  {
    "id": "209002390257532938",
    "Server": "Pokemon Go",
    "Name": "90plus_iv"
  },

it has a very good bot publishing verified coords. Thanks.

**Comment by adrian089089** [comment]
Same issue using GUI.

**Comment by Ilses** [comment]
Check the wiki -- you can't add custom channels at this time. I believe we already have this channel added to the feed, though. If you're getting UNKNOWN_SOURCE, try grabbing v0.1.3!
