### ISSUE TITLE
UNKNOWN_SOURCE  problem

### ISSUE THREAD

**Issue by drusty94** [5andr0/PogoLocationFeeder#144]
Anyone know how to get rid of 'UNKNOWN_SOURCE' from Location Feeder? Only want a couple discord channels, not the spam from unknow sorce.

**Comment by tensei** [comment]
yes pull and compile code

**Comment by NexLegend** [comment]
If you modified the discord_channel.json, that doesn't really do anything except change what shows up on the console. If you remove it, it still pulls from it. That is just for ease of reference.

**Comment by drusty94** [comment]
seems like its always sniping the default discord channels, and if you delete any start to appear UNKNOWN_SOURCE..

**Comment by luumanhvn** [comment]
damn it, thís  'UNKNOWN_SOURCE'

**Comment by Ilses** [comment]
Closing -- ignore channels will be in next release. Deleting channels now will just make you unable to identify them; hence UNKNOWN_SOURCE
