### ISSUE TITLE
How do I go about integrating this with a bot?

### ISSUE THREAD

**Issue by skellyton5** [5andr0/PogoLocationFeeder#145]
The readme is utterly unhelpful. This shit is actually really hard/frustrating for those of us without extensive python experience.

**Comment by s10035147** [comment]
I didnt even knew what is python (Yea its a snake i guess) and I got it working by following the instructions.

**Comment by bulubebek** [comment]
This shit is just working fine for me. :)
And did you mean you want implement it on python-based bots?

**Comment by skellyton5** [comment]
I'm not sure, I guess Im just missing where these instructions are

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 2, 2016 at 10:06 PM, bulubebek<notifications@github.com> wrote:   
This shit is just working fine for me. :)
And did you mean you want implement it on python-based bots?

**Comment by Ilses** [comment]
? There is no python in our codebase, or, as far as I'm aware, Necro/Mobbot. What exactly are you trying to do?

**Comment by skellyton5** [comment]
All the other bots I've used were in Python. As you can see I know so little about it that I didn't realize your bots used something different. 
But that point is moot, because I'm still having issues installing.

Sent from Yahoo Mail on Android 
 
  On Wed, Aug 3, 2016 at 3:38 PM, Ilses<notifications@github.com> wrote:   
? There is no python in our codebase, or, as far as I'm aware, Necro/Mobbot. What exactly are you trying to do?
