### ISSUE TITLE
0.1.2 CLI build throws a log4net error due to missing files

### ISSUE THREAD

**Issue by shinji257** [5andr0/PogoLocationFeeder#146]
As mentioned in subject.  The zip file for the CLI version is incomplete and is missing the dependent libraries needed for it to run.  The GUI one seems ok for me
![image](https://cloud.githubusercontent.com/assets/261005/17355417/6121488a-591e-11e6-8751-cd8e82349c14.png)
.

**Comment by s4ndman85** [comment]
same issue here...plus if i try the GUI. at soon as i open it it crash, any suggestion about 

log4net problem or the crash problem?

thanks guys

**Comment by Dewamade** [comment]
Use this one its work for me, extract and put it on your exe folder 

[config.zip](https://github.com/5andr0/PogoLocationFeeder/files/399319/config.zip)

**Comment by 5andr0** [comment]
fixed with 1.3
