### ISSUE TITLE
The feature "Copy Cords" is not working. It freezes the program.

### ISSUE THREAD

**Issue by ladymPokeD** [5andr0/PogoLocationFeeder#147]
Please advise?

The program just freezes when I try to copy Cords.

Thanks

**Comment by Ilses** [comment]
I'm not sure if we've addressed this yet. Could you see if this is still the case in 0.1.4? We might be missing error handling if the PogoLocationFeeder does not have permission to access your clipboard.

**Comment by Ilses** [comment]
Going to close this since #195 is a duplicate, but also includes a log.
