### ISSUE TITLE
can we add "snipeonlywhensuperballs"

### ISSUE THREAD

**Issue by Marsinator** [5andr0/PogoLocationFeeder#15]
greater value than? or even mega

right now the option is only here for pokeballs. I've had the bot throw 20 of those at an Ivysaur then it ran. To be fair, it had a catch rate of 2.88%. But most people will snipe for high IV, high cp pokemon. despite most bots using razberries to catch, do you think we could tell the bot to not go sniping without super/megaballs?

**Comment by Ilses** [comment]
This is a FR for NecroBot -- wrong repo.
