### ISSUE TITLE
pokemon filter

### ISSUE THREAD

**Issue by samanasu35** [5andr0/PogoLocationFeeder#150]
I think, you add filter
ex: in json;
pokemon_filter:{dragonite,snorlax,zapdos,raichu,charizard}

and then start program.
program is find only this pokemon

**Comment by Ilses** [comment]
You can already filter pokemon client-side using the PokemonToSnipe list in Necro/Mobbot; we don't really gain anything by adding this to the server since your loopback connection won't be a tighter bottleneck than your internet connection.
