### ISSUE TITLE
Poor collects an hour.

### ISSUE THREAD

**Issue by Melinio** [5andr0/PogoLocationFeeder#152]
Poor collects an hour.

**Comment by Brewfasa** [comment]
good explenation, so detailed and stuff...

but he's right, there are like 100's of coords spammed in discord every minute, and the location feeder only sees like idk 15-20 a minute?

It seems to be skipping a shit ton of discord reports

**Comment by Melinio** [comment]
Если я напишу развернуто, то гугл переводчик перековеркает все так, то что смысл моей писанины потеряется. А Русский язык вы навряд ли понимаете...
По этому и написал коротко и ясно.

Примерно через час-два софт перестает собирать координаты с такой же скорость как при старте. Иногда вообще останавливается.
После обновления вроде стал работать стабильно.

**Comment by Ilses** [comment]
We're working toward cleaning the feed, but I'm closing this since it seems to be describing a client-side metric.
