### ISSUE TITLE
Stuck at "Listening..."

### ISSUE THREAD

**Issue by jinkawasaki333** [5andr0/PogoLocationFeeder#154]
Hi, anyone knows why it is not updating any data?

It stucks at :

```
Listening ...
New connection from 127.0.0.1: ......
```

**Comment by Ilses** [comment]
Odd -- it looks like your local bot connections are working, but you aren't getting feed data. Could you try the latest 0.4.1 release and let me know if this is still occurring?

**Comment by jinkawasaki333** [comment]
@Ilses Oh sorry forgot to close this. The previous release didn't work, and I tried the GUI version. It worked perfectly! Thanks for the great tool. But anyway, now I can just pray for you guys to crack the U6 >.<
