### ISSUE TITLE
I downloaded GUI and No copy Coordinates option Avalaible there 

### ISSUE THREAD

**Issue by starktony1** [5andr0/PogoLocationFeeder#155]
Hi,

I downloaded GUI and No copy Coordinates option Available there . please help

![image](https://cloud.githubusercontent.com/assets/20708547/17362322/41d94c74-5992-11e6-9661-c6c69d5eabf7.png)

**Comment by starktony1** [comment]
BUMP

**Comment by starktony1** [comment]
Please Guide

**Comment by PepoelpepO** [comment]
I need a copy Coordinates option please

**Comment by starktony1** [comment]
@PepoelpepO  I cant find COpy coordinates option
