### ISSUE TITLE
issue pogolocationfeeder copy coordenates

### ISSUE THREAD

**Issue by PepoelpepO** [5andr0/PogoLocationFeeder#156]
When copying pogofeeder coordinates are copied me with the comma (, ) and not with the dot (. )

**Comment by PepoelpepO** [comment]
For example: 	Server: PokemonGo Rare Hunting, Channel: rare_pokemon	Dugtrio	0	34,008950693132	-118,49757264487	01/01/0001 0:00:00 
The coordinates are copied wrong, the coordinates would be so well copied:
34.008950693132,-118.49757264487

**Comment by Brewfasa** [comment]
Server: PokéGO- RARE SPOT & Chat!, Channel: 90plus_ivonly	Missingno	0	22.3331599391	114.160888416	1-1-0001 00:00:00

They are copied with a .   its probably your settings in windows that are set up wrong and gives you a comma
