### ISSUE TITLE
How to snipe a specific channel only?

### ISSUE THREAD

**Issue by 750z** [5andr0/PogoLocationFeeder#158]
title, I changed the discord_channel .json file but I feel like its still getting other channels in the feed as well.

**Comment by starktony1** [comment]
U cant , still its not corrected in recent release and 1.0.0.0 release is not working

**Comment by mhvuze** [comment]
See #123 
It's being looked into but for now it's not possible. Removing channels from the discord_channel.json will solely show them as "Unknown Source" in the bot and won't actually disable them.

**Comment by Ilses** [comment]
An ignore channels feature is slated for our next release! I will update the configuration guide at that time :)

**Comment by Ilses** [comment]
0.1.4 is out! You can now ignore channels by removing them from discord_channels.conf!
