### ISSUE TITLE
Catch exception while launching pokesniper

### ISSUE THREAD

**Issue by dody19852002** [5andr0/PogoLocationFeeder#165]
force closed when i click on pokesnipers option (on win 7 32)

**Comment by 5andr0** [comment]
Not integrated yet. Coming soon

**Comment by ExcuseMi** [comment]
Can you attach the logfile?

**Comment by dody19852002** [comment]
sorry, its works, but limited for 1 account only, only open last registeredURL account. it crashed before because i have not registerURL before using sniper....

**Comment by ExcuseMi** [comment]
We should catch this exception anyway. That should be the fix
