### ISSUE TITLE
WIndows Server 2012 Crash

### ISSUE THREAD

**Issue by Zverbeek** [5andr0/PogoLocationFeeder#17]
Opens up and as soon as listening pops up it closes, no error. Necrobot runs on the server fine. Are there some dependencies I'm missing for this?

**Comment by kolayuk** [comment]
The same on Windows 10 :( and no logs provided

**Comment by kolayuk** [comment]
UPD: Started with debugger and have seen an error message, it was about incorrect login. Make sure you're put in config discord email, not user name.

**Comment by xclusive707** [comment]
on my desktop its running well but on my vps it crashes instant
https://i.epvpimg.com/cFeUb.png

**Comment by Zverbeek** [comment]
I figured it out, it is because Discord requires email verification if u change login locations. Create a new account in ur VPS and use that account instead and it will work, else it will crash forever.

**Comment by xclusive707** [comment]
@Zverbeek thanks buddy u helped me out!
created a new acc and it works fine now

**Comment by Zverbeek** [comment]
You are welcome!

**Comment by Ilses** [comment]
Is this with the release client or the latest master? We should have a message for auth failures as of yesterday's source.

**Comment by Twaan07** [comment]
I don´t know if it will fix my problem, everytime i want to start pogofeeder it crashes down without any error message. I am sure my googlemail login is correct. Anyone got the same issue?

**Comment by xclusive707** [comment]
Yeah we had the same issue just read the posts obove you ;)

**Comment by Twaan07** [comment]
oh i just thought so. But I dont know what you mean with VPS?

**Comment by xclusive707** [comment]
Vps = virtual Server ;)
Nevermind just try the updated Version, ne Problem with discord logins anymore

**Comment by Ilses** [comment]
We have a logs directory in the newer releases, and if you run the CLI version from the terminal, you will still see any errors if it crashes. Could you try with our latest release (v0.1.4) and re-open this if you're still experiencing issues? 

Thanks!
