### ISSUE TITLE
integration with pokesniper2

### ISSUE THREAD

**Issue by Aligfadogan** [5andr0/PogoLocationFeeder#170]
I downloaded PokeSniper2 v1.9 and running it with other protocol feeder and works fine. So my pokesniper is fine.

I downloaded the latest release of this feeder (v 0.1.3)

two issues:

1. my PogoLocationFeeder.GUI.exe does not show that red "snipe" button which appears to be working with pokesniper2 in the video demo; (for some reason I dont have it)
![image](https://cloud.githubusercontent.com/assets/20713230/17370510/e7dd9958-5961-11e6-899a-3e0f4e45ae79.png)

2. How do I config pokesniper2 to listen to this feeder? their user.xml settings does not have such option. Do I need to change the source code'?

**Comment by ExcuseMi** [comment]
1. For now you have to run registerurl.bat in the pokesniper2 folder.
You need the lastest version of pokesniper2 for this.
2. Pokesniper2 doesn't listen to the feeder. This is functionality that should be implemented in pokesniper2.

**Comment by paperc07** [comment]
See my problem is, when necro doesn't see the pokemon, I will hit the "red bullseye" to manually do it and it loads up pokesniper, logs me in, searches the area, but only twice it has worked and I didn't get softbanned?

**Comment by Marsinator** [comment]
you have to close necro to not get softbanned doing that

**Comment by TheGoGlider** [comment]
@ExcuseMi there is no registerurl.bat

**Comment by Marsinator** [comment]
there is. in the sniper folder

**Comment by IMRastafari** [comment]
So, how to make it work together?
Whats the point adding not working function?

**Comment by Roxazlp** [comment]
![sniper](https://cloud.githubusercontent.com/assets/20785720/17379216/ab6094b6-59c1-11e6-998a-b7a0cb4ab806.PNG)

Did you download the latest pokesniper2 version? It's 1.9 
https://mega.nz/#!CRtUyASA!b1FHk3qeT2OxKUea0FykEoeEXd2PiBt1bLfZq4caadw

Working for me and you can't run necro / mobbot with pokesniper 2, cause this will cause a softban for you.

![sniped](https://cloud.githubusercontent.com/assets/20785720/17379298/0900677c-59c2-11e6-87e7-d5b68155a742.PNG)

**Comment by ExcuseMi** [comment]
In the next version you'll be able to configure where the pokersniper2 exe is located.
Then you won't need to run the registerurl.bat. Hope this will cause less confusion on how to setup this feature.
