### ISSUE TITLE
Discord authorization

### ISSUE THREAD

**Issue by t-p-l-k** [5andr0/PogoLocationFeeder#171]
Can you explain how app connects to discord now?
Why no login/password in config file?

**Comment by tangdami** [comment]
Looks like it doesn't require you to connect your account...

**Comment by Ilses** [comment]
Discord staff have provided us with a dedicated feed at pogo-feed.mmoex.com/messages

(See wiki for more information)

**Comment by t-p-l-k** [comment]
@Ilses oh, it's cool. Thanks for explanation!
