### ISSUE TITLE
Why not as the author shows, in front of the icon has pets sight icon?

### ISSUE THREAD

**Issue by 1299474805** [5andr0/PogoLocationFeeder#175]
Why not as the author shows, in front of the icon has pets sight icon?
![qq 20160804004031](https://cloud.githubusercontent.com/assets/20820382/17373731/1270413c-59dc-11e6-9933-980a4db39b8e.png)

**Comment by LiliumElfenLIED** [comment]
You have PokeSniper 2 1.9 ? 

If yes go run registerurl.bat and have fun else go download :D.

**Comment by 1299474805** [comment]
Thank you very much, the problem is solved.

**Comment by LiliumElfenLIED** [comment]
Your welcom ;).

**Comment by tensei** [comment]
closing
