### ISSUE TITLE
Issue that need to be fixed.

### ISSUE THREAD

**Issue by am3yar0ra** [5andr0/PogoLocationFeeder#182]
![image](https://cloud.githubusercontent.com/assets/1933816/17377411/2a8e4c6e-59d7-11e6-83de-889ed71d8a56.png)

**Comment by tensei** [comment]
?

**Comment by Ilses** [comment]
That's fine -- it's just the default if we're unable to parse the pokemon name. We'll work on cleaning the feed in future releases!
