### ISSUE TITLE
Help with discordbot

### ISSUE THREAD

**Issue by phr34k0** [5andr0/PogoLocationFeeder#187]
So how do you use this pogofeeder to scrape channels and post it to your server channel?

**Comment by Roxazlp** [comment]
It gets coords + pokemon name and sometimes IV-stats from discord-channels, if activated also pokesnipers and trackemon.
The coords + pokemon are being used to snipe the pokemon with either a bot (f.e. mobbot or necro) or pokesniper2.

**Comment by phr34k0** [comment]
Been following this repo for quite sometime and i noticed there used to be a function setting that we used to be able to add bot discord token. Apparently it was removed. I have my own discord server and this repo currently doesnt scrape discord channels https://github.com/enjoy2000/discord-pokemon-go-snipe-bot

**Comment by Roxazlp** [comment]
My questions would be, why would you want to scrape channels and repost it to your own server channel?
Pogofeeder is already doing the work for you.

**Comment by phr34k0** [comment]
Yes.. exactly that. You are repeating my question lolol.

**Comment by Ilses** [comment]
Check the wiki -- that feature was removed because we were contacted by Discord staff about traffic issues. Instead, Discord has provided us with a dedicated feed. If you would like your server's channels added to the feed, you can open a [Channel Request]. Otherwise, you can use the project you linked to copy one channel's data to another.

**Comment by phr34k0** [comment]
I noticed pogofeed is fetching data from pogo-feed.mmoex.com/messages . Reason to reposting to server channel is that, some users doesn't even know how to run pokesniper and manually use the coords to spoof their location in the game.

@Ilses : Aye thanks!

**Comment by Ilses** [comment]
Ah, legacy users. Ok, that makes more sense. It would probably be more future-proof if they started autosniping (or used the new PokeSnipers2 integration). I guess the spirit of the question doesn't exactly fit this project -- it's more of a personal help thing (and we're trying to kill off manual sniping, after all ;) ), so I'll be closing this.
