### ISSUE TITLE
why cant i see the issues tab on another users/program?

### ISSUE THREAD

**Issue by Epic81** [5andr0/PogoLocationFeeder#191]
I was able to read and write comments in  the issues section of https://github.com/1461748123/Pokemon-Go-Rocket-API/tree/master but now i cant find the tab or any of my issues i needed help with or i was helping others with???? I went to my history tabs in fire fox and selected all pertaining to github
some display 404 error page and the ones that do open dont have the comments/issue tab???/ HELP

**Comment by tensei** [comment]
has nothing todo with this repo.
probably disabled issues
