### ISSUE TITLE
Wiki Instructions too vauge

### ISSUE THREAD

**Issue by skellyton5** [5andr0/PogoLocationFeeder#192]
http://prntscr.com/c1ejkf

**Comment by Ilses** [comment]
Cleaned them up a bit -- I will assume you know what you're doing if you build from source.

**Comment by skellyton5** [comment]
I'm not though. I have a copy of PokeMoBot and im trying to integrate this. 
Sent from Yahoo Mail on Android 
 
  On Wed, Aug 3, 2016 at 10:56 PM, Ilses<notifications@github.com> wrote:   
Cleaned them up a bit -- I will assume you know what you're doing if you build from source.
