### ISSUE TITLE
0.1.4. Crashes at start

### ISSUE THREAD

**Issue by DrakeLyon** [5andr0/PogoLocationFeeder#196]
I'm not sure why, but as soon as I try to open this latest release, Windows gives me an error saying "PogoLocationFeeder.GUI has stopped working. This is odd because it worked perfectly fine beforehand.

EDIT: NEVERMIND, I guess it only needed to be ran as an administrator.

**Comment by tensei** [comment]
log?

**Comment by DrakeLyon** [comment]
I'm sorry, I just jumped the gun on this one. It just needed to be ran as an administrator..

**Comment by Ilses** [comment]
Huh, you shouldn't need to run it as an admin. At least, I don't... Might be a firewall issue?

**Comment by DrakeLyon** [comment]
No it's very odd. The version beforehand didn't need administrative privileges or anything.
