### ISSUE TITLE
Anyone can generate a "PokemonToSnipe (List)" for me?

### ISSUE THREAD

**Issue by sammy6369** [5andr0/PogoLocationFeeder#201]
Once PogoLocationFeeder give you a pokemon coordinate and name,
Issue: the bot do not snipe unless you put the name of the pokemon in the list.
Request: Thats why I need a PokemonToSnipe (List) with all pokemon. Thanks very much.

**Comment by Ilses** [comment]
This is a request for a client-specific config, and is not related to this server project. Furthermore, I have a reasonable list on the wiki already, and generating a full pokemon list would take all of two minutes.

I might update the default list at some point, but bot updates aren't finished yet.

**Comment by Ilses** [comment]
(It occurred to me that Necro's default probably needs to be updated: a blank pokemon to snipe should ==> snipe all pokemon. I'll make a TODO, but it's not a priority right now).
