### ISSUE TITLE
Trackemon not working anymore in v0.1.4

### ISSUE THREAD

**Issue by djdookie** [5andr0/PogoLocationFeeder#204]
From the current logfile v0.1.4:

Error trying to get a sessionId for Trackemon: Der Remoteserver returned an error: (503) Server not available.
Trackemon: No valid session found!

Reason: cloudflare? They also seem to use cloudflare now like pokesnipers.

**Comment by dakb** [comment]
same here..
`Error trying to get a sessionId for Trackemon: The remote server returned an error: (503) Server Unavailable.`

**Comment by FVKUALL** [comment]
Change this to true:
"UsePokeSnipers": true,
in the Config/config.json

**Comment by ExcuseMi** [comment]
We will add a ton of new sites in the new release. We're gonna remove trackemon until we get it fixed.
