### ISSUE TITLE
Location feeder not connecting to discord

### ISSUE THREAD

**Issue by redline187** [5andr0/PogoLocationFeeder#21]
if i use token to connect discord then it says this

D:\pokemon\pogo\PogoLocationFeeder\bin\Release>PogoLocationFeeder.exe
Listening...

D:\pokemon\pogo\PogoLocationFeeder\bin\Release>

the program just shutdown

and if use DiscordUser/Password then i get this

D:\pokemon\pogo\PogoLocationFeeder\bin\Release>PogoLocationFeeder.exe
Listening...
Failed to authroize Discord user! Check your config.json and try again.
^C
D:\pokemon\pogo\PogoLocationFeeder\bin\Release>

only pokesnipers.com is working.

**Comment by sliverfishes** [comment]
I had the problem before and they said only people with permission can use tokens. Normal users have to login with email/pass.

**Comment by Ilses** [comment]
Token login is for bot users. Bots must already be invited to servers whose channels they wish to scrape.

Try logging into the discord app on your browser in a private browsing session and verify your credentials are correct.

**Comment by Ilses** [comment]
Since we no longer support token / auth logins, I am closing this issue. Please update to the latest release! https://github.com/5andr0/PogoLocationFeeder/releases
