### ISSUE TITLE
Add PokeSnipe Channel

### ISSUE THREAD

**Issue by jirenax** [5andr0/PogoLocationFeeder#210]
add pokezz.com to the channel list

**Comment by vapp13** [comment]
I've been tracking this one and looks very solid.
http://pokespawns.be/

**Comment by NicJames2378** [comment]
Or rather, perhaps we could get an additional .json configuration file that would allow us to add/remove URLs to snipe from, including [https://pokezz.com/pokemons.json], [pogo-feed.mmoex.com], [http://pokesnipers.com/api/v1/pokemon.json], [https://pokewatchers.com/api.php?act=grab], and possibly pokespaawns.be (though I could not locate an APi for the last one). If not adding the configuration file, maybe it could be implemented into the PoGo-Feed to have the others compiled and streamed via it similar to how PokeSnipers is?

**Comment by jamalbaharun** [comment]
how to add a discoord channel?
