### ISSUE TITLE
What do i do?

### ISSUE THREAD

**Issue by missyyou94** [5andr0/PogoLocationFeeder#214]
My bag is limited.
I want to keep hyper potion and max potion instead potion? 
I want to keep max revive instead revive?
I want to keep ultra ball, greater ball instead pokeball?
And what do i do?

**Comment by saahilz** [comment]
edit your config dude , it's in the config folder, scroll and find the line and edit save

**Comment by missyyou94** [comment]
i'm so sorry, Thanks for your prompt.

**Comment by vapp13** [comment]
The bot is smart, it will always try to keep always your best item: ie: ultraball>greatball>pokeball
"TotalAmountOfPokeballsToKeep": 200,
"TotalAmountOfPotionsToKeep": 40,
"TotalAmountOfRevivesToKeep": 10,
"TotalAmountOfBerriesToKeep": 40,

**Comment by Ilses** [comment]
This question is about bot config and does not relate to this project. Closing.
