### ISSUE TITLE
"You'll need a new app to open pokesniper2"

### ISSUE THREAD

**Issue by Kendama165** [5andr0/PogoLocationFeeder#216]
For some reason when ever I'm trying to click the target icon that's what I get. Any fix ?

**Comment by Lim-Dul** [comment]
Got this as well. Might be a Windows 10 issue.

The path to Pokesniper2 is D:\<Username>\Desktop\PokemonGO\PokeSniper2\PokeSniper2.exe

Is the config correct? I used double-backslashes for the path in the config file.

**Comment by tensei** [comment]
go in gui settings and double click the textbox and select your folder 
don't do it manually in the config

**Comment by Kendama165** [comment]
that's what I did, still giving me this issue.

https://gyazo.com/c8cbe602ef278e2081c25165fe0be955

**Comment by Lim-Dul** [comment]
I did it both ways. Still, I got this weird message.

![pokesniper2](https://cloud.githubusercontent.com/assets/428324/17464965/c0488a38-5cea-11e6-9ea4-97e48fca22af.png)

**Comment by tensei** [comment]
permission problem ? try starting it as administrator

**Comment by Lim-Dul** [comment]
Nope, didn't help.

**Comment by tensei** [comment]
ugh... did you use the registerurl.bat in pokesniper folder?

**Comment by Sulfuras** [comment]
can confirm... registerurl.bat in the pokesniper folder fixed the issue

**Comment by tensei** [comment]
nvm found the error

**Comment by Lim-Dul** [comment]
OK, thanks for the help. Was more of an issue with PokeSniper2 then. :)

registerurl.bat fixed the issue for me as well.

**Comment by tensei** [comment]
i found a error too, should be fixed next release
