### ISSUE TITLE
weird no mons listed in feeder weird error in debug

### ISSUE THREAD

**Issue by snowballfred** [5andr0/PogoLocationFeeder#227]
https://gyazo.com/252bacd3e1e0926618ee77b2e4f09384

**Comment by ExcuseMi** [comment]
this is an issue related to the GUI depending on .NET 4.6.1 and the client only on 4.5.2.
The next release will be fully 4.5.2 compatible. (wait a couple minutes / hours or install .NET 4.6)

**Comment by snowballfred** [comment]
thanks bro cheeers for the info
