### ISSUE TITLE
PokeSnipers2 EXE

### ISSUE THREAD

**Issue by ImaDinoRar** [5andr0/PogoLocationFeeder#234]
I am having a problem in PogoLocationFeeder, I fill out Line 7 in config.json ("PokeSnipers2Exe") Example : http://prntscr.com/c2weop but I get this error: http://prntscr.com/c2wh1n. To try troubleshooting this on my own I have changed PokeSniper2.exe to PokeSnipers2.exe with no positive results. I have also tried changing the dir to : C:\Users\MyName\Desktop\PokeStuff\PokeStuff\PokeSniper2_v1.10 and C:\Users\MyName\Desktop\PokeStuff\PokeStuff\PokeSniper2_v1.10\ I tried all three Dir with PokeSniper2.exe and Pokesipers2.exe with no results. Any fix?

**Comment by tensei** [comment]
open gui and set the path in there don't edit the config.json

**Comment by facinick** [comment]
where to get pokesnipe 2 exe file?

**Comment by tensei** [comment]
google

**Comment by ImaDinoRar** [comment]
@tensei I am not using the GUI I would rather use the Command Prompt window..
