### ISSUE TITLE
PokeSniper Error

### ISSUE THREAD

**Issue by sinisteraura** [5andr0/PogoLocationFeeder#235]
Whenever I try to use the target button to sniper, I get the following error:
"Could not load settings. user.xml either missing or malformed."

PokeSniper2 works just fine for me when I paste coordinates or use links from PokeSnipers.com

**Comment by tensei** [comment]
update pokesniper2

**Comment by sinisteraura** [comment]
I have PokeSniper2 v1.11 already.

**Comment by igoticecream** [comment]
Its a bug from v 1.5.0, not the version of sniper

https://github.com/5andr0/PogoLocationFeeder/issues/232 for the solution

**Comment by sinisteraura** [comment]
Placing it into the folder fixed it. Thank you very much.

**Comment by tensei** [comment]
@sinisteraura @igoticecream do me a favor and post the debug output after you press the snipe button

**Comment by sinisteraura** [comment]
@tensei I don't get anything in the actual program's debug. I just checked the PokeSniper2 log file that was generated which just returned the message I have in the original issue post.
