### ISSUE TITLE
automatically recycle pokeball when bag is full, mayoritas greatball and other

### ISSUE THREAD

**Issue by cikenpukpuk** [5andr0/PogoLocationFeeder#239]
when my bag is full, and then my pokeball 100++ thats bot not recyle my pokeball, but just got notification "cant loot bag is full ". help for this. Thanks

**Comment by cikenpukpuk** [comment]
![capture_1](https://cloud.githubusercontent.com/assets/20737801/17474760/e0a501b6-5d81-11e6-80a8-4b68c29a5504.png)

**Comment by qu4qu4** [comment]
it's about your bot setting

**Comment by ExcuseMi** [comment]
This is related to the bot, not pogolocationfeeder
