### ISSUE TITLE
Sniping with pokesniper2 not working?

### ISSUE THREAD

**Issue by ivanders21** [5andr0/PogoLocationFeeder#246]
Hello,

i already copy ALL the pogo location feeder Files into pokesniper2 folder, then when i click on pokemon in pogo feeder, it says logging in then automatically close
help please?
thanks

**Comment by P4R4DiSi4C** [comment]
Hello,
Same here, instant close after this message:
[https://puu.sh/qtZUh/db608adfdc.png](url)

**Comment by ExcuseMi** [comment]
Duplicate of #242
