### ISSUE TITLE
Issue with pogo feeder while using pokesnipers2

### ISSUE THREAD

**Issue by Warrfare** [5andr0/PogoLocationFeeder#255]
I followed a step by step guide on how to get these programs working together.

Everything seemed to be set up correctly and I extracted Pogo location Gui, Cli, and pokesniper2 into the same folder. 

But when I click the crosshair to snipe a pokemon the program opens up and says....
Logging in.....
Looking for (pokemon) in (lat) (Long)

Then not even 2 seconds after it pops up with the "Looking for (pokemon) in (lat) (Long)" prompt the whole program closes out.

Does anyone have any ideas to help me out?

This was the guide I followed : http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/570325-how-fix-user-xml-malfunction-pogolocationfeeder.html

**Comment by sp7759** [comment]
i had that problem on 1,15 on 1.14 is working fine

**Comment by Wasted2016** [comment]
use it like this 

"PokeSnipers2Exe": "C:\\Users\\casen\\Desktop\\pokemon\\Pokesniper\\PokeSniper2.exe",

instead of 

"PokeSnipers2Exe": "C:\Users\casen\Desktop\pokemon\Pokesniper\PokeSniper2.exe",

**Comment by Ilses** [comment]
I haven't looked at more recent versions of pokesniper, but I've heard reports that it also works on v1.11
