### ISSUE TITLE
[10:44:04][WARN] Error  System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by vfuyong** [5andr0/PogoLocationFeeder#263]
Guess some API provider has blocked the feeder?

**Comment by filo4u** [comment]
I am also having this issue and I believe this is what's causing the crashes.  Specifically 188.165.224.208:49006 is refusing connection.

**Comment by ravencrest31** [comment]
hey it's happening too in my computer. please fix it bro

**Comment by filo4u** [comment]
Found a fix. Change pokespawns to false in the config.
  "UsePokeSpawns": false,

Pokespawns is down and this is causing the issue.

**Comment by ifbatmanwasreal** [comment]
@filo4u what line in what file is that in?
