### ISSUE TITLE
didn't find a pokemon within the SnipingScanOffset

### ISSUE THREAD

**Issue by STCOZT** [5andr0/PogoLocationFeeder#275]
I am always getting this error, rarely it catches some pokemon but its time consuming. tried almost every way to solve it but it seems there is a general error that most people suffering. Any solution that will help will be appreciated :)

**Comment by Bigg-Mike** [comment]
Same error.

**Comment by Velorianvx77** [comment]
Same!

**Comment by bassemmixez** [comment]
same

**Comment by xuninho** [comment]
Same

**Comment by egotrip77** [comment]
same :(

**Comment by pehur** [comment]
Same, and somehow i still get locations through some mystery servers?

{
  "Port": 16969,
  "UsePokeSnipers": false,
  "UsePokezz": false,
  "UsePokeSpawns": false,
  "UsePokewatchers": false,
  "PokeSnipers2Exe": "",
  "RemoveAfter": 15,
  "ShowLimit": 2
}

Still getting results from pokéGO - RARE SPOT & Chat!

How can i turn this off?

**Comment by Ghenghis** [comment]
any way to make it auto scan Offset by it self?

SnipingScanOffset error

  "SnipingScanOffset": 0.001,
  "SnipingScanOffset": 0.0001,

have tried a few different settings but cant figure it out. any way to make it auto search by it self?
