### ISSUE TITLE
Failed to authroize Discord user! Check your config.json and try again.

### ISSUE THREAD

**Issue by zhu8808** [5andr0/PogoLocationFeeder#28]
The discord username and password are correct.

**Comment by miracho** [comment]
me too

**Comment by septemus** [comment]
Discord servers are having a bad time.

**Comment by Ilses** [comment]
Yeah, discord servers have been hurting:
https://status.discordapp.com/

I'm marking this as a known bug on the wiki sidebar, since the error message is misleading.
