### ISSUE TITLE
Unable to load DLL' Resources/encrypt.dll ERROR

### ISSUE THREAD

**Issue by ggcollins** [5andr0/PogoLocationFeeder#283]
Can someone help me ? My necroBot opens and displays the following error message:
Unable to load DLL' Resources/encrypt.dll ERROR

already I tried reinstalling the programs , but does not work . continues even giving error

even I tried using another account , and still gives same error.

also appears the message has not been possible to find the specified module ( exception from HRESULT: 0x8007007E )

**Comment by BobbyWibowo** [comment]
You're getting that error with NecroBot, right? Ever thought about reporting there instead? I mean, this repo is for the feeder.
