### ISSUE TITLE
System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.

### ISSUE THREAD

**Issue by mensurdurakovic** [5andr0/PogoLocationFeeder#284]
Using on Windows 7 (I think this problem is related only to Win 7), after running fine for couple of hours PogoLocationFeeder then just crash. GUI version becomes unresponsive and crashes, CLI just does not work anymore after that. Full error log looks like this:

```
System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at PogoLocationFeeder.Repository.PokezzRarePokemonRepository.<StartClient>d__7.MoveNext()
[2016-08-09 00:49:11][WARN] Error

System.PlatformNotSupportedException: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.ClientWebSocket..ctor()
```

Anyone experiencing same issue ?

**Comment by kalilc** [comment]
U guys will report this issue hour by hour? ITS CONFIRMED W7 PROBLEM 0.15 SAYS "PROBLEMS ON W7" IF YOU HAVE PROBLEMS AND YOU'RE ON W7 THAN OBVIOUSLY IS THAT.

**Comment by SYNurg** [comment]
@mensurdurakovic @kalilc ,  I am running windows 7; had the same issue. Downloaded the source and did the build with VS, not getting the error any more.

**Comment by kalilc** [comment]
Of course, version 0.16 is out and its working on w7 again.

**Comment by mensurdurakovic** [comment]
@kalilc thank you, I will try it asap
