### ISSUE TITLE
[Channel Request] Three Channels

### ISSUE THREAD

**Issue by Pingren** [5andr0/PogoLocationFeeder#286]
https://discord.gg/yAEfFgv
high-iv-coords

https://discord.gg/XNArZz8
high_iv_pokemon

https://discord.gg/qvpku
90iv_above

**Comment by BRZ420** [comment]
expired

**Comment by PalmerX** [comment]
https://discord.gg/jz6F8
high-iv-coords

https://discord.gg/PV7Gs
high_iv_pokemon

https://discord.gg/3QudG
90iv_above

**Comment by Ilses** [comment]
Sorry, just getting around to these. Could you post a permanent invite, or send me a discord DM? Thanks!
