### ISSUE TITLE
[Request] Disable Filter in config.json

### ISSUE THREAD

**Issue by kevinpark1217** [5andr0/PogoLocationFeeder#288]
Please add a configuration in config.json that allows filters to be disabled. I personally like to snipe all kinds of Pokemon, whether it's good or bad.

**Comment by vfuyong** [comment]
Second it

**Comment by tensei** [comment]
put all pokemon's in list

**Comment by TankTheFrank** [comment]
The bot should do the filtering anyway not the location feeder. The feeder should check if they are real or fake.

**Comment by BobbyWibowo** [comment]
+1, had to use old version because deleting the `filter.json` will still make the feeder skipping everything.

**Comment by tensei** [comment]
[put everything in right list and click Filter button again to save](http://i.imgur.com/zgMAdUN.gifv)

**Comment by BobbyWibowo** [comment]
@tensei Except I was using the CLI version since the GUI was too much for my simplicity need. So if you can possibly provide me with a filter list which has literally all available Pokemon name instead, that'd be much better.
