### ISSUE TITLE
how to delete server "pokesnipers"

### ISSUE THREAD

**Issue by Hinau** [5andr0/PogoLocationFeeder#294]
hey,
is there any opportunity to delete the server "pokesnipers" because it spams the whole box with useless pokemons. I couldnt find it in the discord channel config file. So.. how i delete it?

**Comment by Sylencer90** [comment]
Yeah i enjoyed the time when there was actually no fake pokemon locations. Now they all get greedy and drag ppl into donating...

**Comment by BobbyWibowo** [comment]
You can disable it from the `config.json` file. I personally only use the discord channels.

**Comment by Hinau** [comment]
Thank you very much!
