### ISSUE TITLE
Unhandled exception: Discord.net.Timeoutexception

### ISSUE THREAD

**Issue by icrona** [5andr0/PogoLocationFeeder#31]
![image](https://cloud.githubusercontent.com/assets/19201715/17277982/5e346bde-577a-11e6-8153-db3c7c3953c5.png)

**Comment by t-p-l-k** [comment]
#29 Same

**Comment by icrona** [comment]
try and try again..
suddently it work just fine..

**Comment by djbie** [comment]
try and try not work for me :(

**Comment by Maxeemo** [comment]
me too :|

**Comment by t-p-l-k** [comment]
https://status.discordapp.com/
Looks like it's discord server side problem.

**Comment by djbie** [comment]
connectivity issues with server, any other source?

**Comment by Ilses** [comment]
We were contacted by discord staff about traffic issues -- see the wiki for details. Please update to the latest release; discord authentication is no longer required! https://github.com/5andr0/PogoLocationFeeder/releases
