### ISSUE TITLE
Pokésniper2 ask me confirmation before chatching?

### ISSUE THREAD

**Issue by Real96** [5andr0/PogoLocationFeeder#313]
Every time I want to catch a pokemon, Pokesniper ask me to click Enter to confirm or X to decline (as you can see here http://imgur.com/fplGMX5).
How can i disable it to make it catch pokemon without my confirmation? It says it can be done from settings, but i can't find this option....

**Comment by ExcuseMi** [comment]
It should be this setting:

<RequireURLConfirmation>false</RequireURLConfirmation>
