### ISSUE TITLE
keeps crashing 

### ISSUE THREAD

**Issue by paperc07** [5andr0/PogoLocationFeeder#317]
every 30mins to 2 hours it just crashes

**Comment by ExcuseMi** [comment]
We are trying to locate the problem. Is this in the GUI app?

**Comment by Zenotron** [comment]
Yes this is with the GUI, I have the same problem.

**Comment by CalmerThanTheDude** [comment]
Mine crashes on start. I restarted it and now it's complaining that I have to edit config.json, however it's the stock default one, not sure what I have to edit on there.

**Comment by OmegaXeroxer** [comment]
@CalmerThanTheDude Mine did that so I just used the old config file from 1.6 and it worked fine. I guess the last two lines are not necessary/mess it up? I'm playing around with it though, but that's a quick fix if you need it.

New:
{
  "Port": 16969,
  "UsePokeSnipers": true,
  "UsePokezz": true,
  "UseRareSpawns": true,
  "UsePokewatchers": true,
  "PokeSnipers2Exe": "",
  "RemoveAfter": 15,
  "ShowLimit": 30,
  "VerifyOnSkiplagged": true,
  "UsePokemonGoIVClub": true
}

Old:
{
  "Port": 16969,
  "UsePokeSnipers": true,
  "UsePokezz": true,
  "UseRareSpawns": true,
  "UsePokewatchers": true,
  "PokeSnipers2Exe": "",
  "RemoveAfter": 15,
  "ShowLimit": 30,
}

**Comment by CalmerThanTheDude** [comment]
@OmegaXeroxer Thanks for sharing your config file. For whatever reason I restart it and every other restart it crashes then works, it's really strange. I'm also not getting anything from discord feeds. Isn't it supposed to be getting push notifications from the discord channels?

I'm getting all the website coordinates, it's pulling those from their API's just fine, it's not getting anything from discord though.
