### ISSUE TITLE
Values working improperly   "MinPokeballsToSnipe": 100,   "MinPokeballsWhileSnipe": 50,

### ISSUE THREAD

**Issue by catalinutzz** [5andr0/PogoLocationFeeder#321]
So,as you can see in the first image # 
![prova2](https://cloud.githubusercontent.com/assets/20958179/17578014/7f373520-5f84-11e6-9756-58409985dd2f.png)

It is farming just fine(i made this own setup,150k xp no egg and no evolution etc)
but that's not the issue that i'm going to talk about.So as you can see it is farming without catching pokeballs in the pokestop or recyclying pokeballs/rawsberries/potions(not needed because it is consuming them) and no transfering pokemons,yea you may say!WOW THAT'S so nice it will repeat this cycle over and over again.NOPE.

This is the second screenshot
![prova1](https://cloud.githubusercontent.com/assets/20958179/17578073/2bed2ce8-5f85-11e6-9d69-c720603d0994.png)

This is the same bot as before,just 3 minutes later,you can check the time.Well,here the cycle it's fu@@ed up,random recycling ,random catching pokeballs,going to pokestopts etc.
the values of minpokeballstosniper were as the one in description.You can see that it has enough pokeballs to repeat that cycle again but it just doesn't care ..It keeps getting random pokeballs even if he has more than 150 on  "MinPokeballsToSnipe": 100 .
You are right.. this is perfectly normal,it has more than minpokeballs to sniper ,and more than minpokeballs while snipe?"why are you complaining about"??? Well, why doesn't it follow the same path with screenshot 1 ? or viceversa? this feature was enabled in 0.7.0 version where "MinPokeballsWhileSnipe": 50, WAS MISSING.

This is a screenshot with 0.7.0 version
![prova 3](https://cloud.githubusercontent.com/assets/20958179/17578272/1ff4d664-5f87-11e6-9886-ae18577dda6b.png)

as you can see here the bot in the first image work like the one in the third.,BUT THE THIRD bot KEEP THAT CYCLE ,not as the first bot that go crazy after a while.Let me make an example:

how's working the bot in the third image(v 0.7.0)
1)catchingpokemon
2)catchingpokemon
3)catchingpokemon
4)then he run out of pokeballs,                          (it's not proved in the screen but i can send you the cfg
5)go on pokestops to refull pokeballs,rawsberries etc          (to test for your self that is working this way)
6)it transfere all the pokemon that are on transferlist.
1)catchingpokemon
2)catchingpokemon
3)catchingpokemon
4)then he run out of pokeballs,
5)go on pokestops to refull pokeballs,rawsberries etc 
6)it transfere all the pokemon that are on transferlist.

and keep forever this cycle.

NOW,the bot in the first image (v 0.8.7)

**Comment by tensei** [comment]
wrong repo

**Comment by catalinutzz** [comment]
updated,i wrongly pressed enter instead of going new line.
