### ISSUE TITLE
cant even get the pogo started

### ISSUE THREAD

**Issue by twinbladez** [5andr0/PogoLocationFeeder#325]
First by default, i need to click it twice just to open. 

Opened(first time), debug console says error in config.json so I put the pokesnipers2 folder with this config

{
  "Port": 16969,
  "UsePokeSnipers": true,
  "UsePokezz": true,
  "UseRareSpawns": true,
  "UsePokewatchers": true,
  "PokeSnipers2Exe": "D:\Downloads\pokesnipers2",
  "RemoveAfter": 15,
  "ShowLimit": 30,
  "VerifyOnSkiplagged": false,
  "UsePokemonGoIVClub": true
}

After that, it wont even start up. It will just crash.

**Comment by pavog** [comment]
What happens if you use the default config?
```
{
  "Port": 16969,
  "UsePokeSnipers": true,
  "UsePokezz": true,
  "UseRareSpawns": true,
  "UsePokewatchers": true,
  "PokeSnipers2Exe": "",
  "RemoveAfter": 15,
  "ShowLimit": 30,
  "VerifyOnSkiplagged": true,
  "UsePokemonGoIVClub": true
}
```
If this does not work try to delete (or rename) your config.json and start the LocationFeeder.
It should first open the window and close it immediately to create the config. If you start the LocationFeeder again it should work.

**Comment by twinbladez** [comment]
I got it working by just clicking the empty blank space on the sniper2 section of the GUI Settings. Thanks though.
