### ISSUE TITLE
Pogolocationfeeder v0.1.6 keeps on crashing after an hour

### ISSUE THREAD

**Issue by Timangzkie** [5andr0/PogoLocationFeeder#331]
What to do?

**Comment by Sainver** [comment]
use CLI version

**Comment by Timangzkie** [comment]
Any link?

**Comment by ExcuseMi** [comment]
Please try with https://github.com/5andr0/PogoLocationFeeder/releases/tag/v0.1.7
We cleaned up some issues that could have caused this.
