### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by Paowiii** [5andr0/PogoLocationFeeder#337]
because it only says no snippable pokemon found.

it's not sniping?

is it down?

**Comment by jchilcher** [comment]
no pokemon showing up on my end either

**Comment by RadicalRordan** [comment]
Seetings > deactivate Verify on Skiplagged than restart PoGo Feeder

**Comment by jchilcher** [comment]
>  RadicalRordan commented a minute ago
> Seetings > deactivate Verify on Skiplagged than restart PoGo Feeder

Fixed it.
