### ISSUE TITLE
Setting a pokesniper2.exe location in config.json makes software crash on start

### ISSUE THREAD

**Issue by CalmerThanTheDude** [5andr0/PogoLocationFeeder#340]
As the subject says PoGoLocationFeeder crashes on start if a pokesniper2.exe location is set in the config. The path to the exe is very simple and has no spaces.

I tried setting the direct .exe path and also just the folder path, either way it crashes on start unless the folder path is removed from the config.

Also verifying with skiplagged at the moment makes it so the software doesn't do anything at all with discord coordinates. Disabling skiplagged verification makes discord sniping work again.

Also can't paste or set anything in the pokesniper folder location in the Settings section of the software.

Running .NET 4.6.2 clean install of it. On Win7 x64.

**Comment by AxelReshiram** [comment]
Me too !

**Comment by Skyll** [comment]
same issue

**Comment by Skyll** [comment]
Fix: http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/570325-how-fix-user-xml-malfunction-pogolocationfeeder.html#post3528060

**Comment by CalmerThanTheDude** [comment]
@Skyll Thanks for that fix, btw you don't have to copy the contents of the PokeSniper2 zip file into the PoGo Location feeder like the guide says, you can simply double click the path location and choose wherever else you installed it. Mine works with just doing that.

I also see why the crashes are happening when manually adding a path. It needs double back slashes in the path, for example:

INCORRECT:

"C:\PokeSniper2\PokeSniper2.exe"

CORRECT:

"C:\\Pokesniper2\\PokeSniper2.exe"
