### ISSUE TITLE
Suggest skiplagged verification to be failopen

### ISSUE THREAD

**Issue by vfuyong** [5andr0/PogoLocationFeeder#343]
Currently it appears if skiplagged is not usable, no coordinates will be attempted. It makes more sense to still try those coordinates even not verified.

**Comment by ExcuseMi** [comment]
Yes, you are right, the mechanism for this was in place but the errors didn't correctly detected.

**Comment by vfuyong** [comment]
Understood ;) great effort, great project. I just hope there is some reliable way to get verified coordinates without dependency on external sites.
