### ISSUE TITLE
Instant softban

### ISSUE THREAD

**Issue by willbp** [5andr0/PogoLocationFeeder#346]
I use necro 0.85 with location feeder, when i click to pick one pokemon i get instant soft ban always! Help pleaseee
![image](https://cloud.githubusercontent.com/assets/17730255/17610198/eab139e4-6011-11e6-88e5-9c48aefa7c78.png)

![image](https://cloud.githubusercontent.com/assets/17730255/17610213/1c06bdb6-6012-11e6-9649-43aa226adc3e.png)

**Comment by vfuyong** [comment]
I don't recommend you to use pokesniper2 exe. It is not a good idea with necro.

**Comment by willbp** [comment]
what you use?

**Comment by vfuyong** [comment]
necro has sniping function that works with pogo location feeder. Pokesniper2 is just another tool that does the same.
