### ISSUE TITLE
Failed to authroize Discord user! Check your config.json and try again.

### ISSUE THREAD

**Issue by srmanuel** [5andr0/PogoLocationFeeder#35]
I get this message all the time after this night, this afternoon it was working perfectly.

Failed to authroize Discord user! Check your config.json and try again.

I know for sure that the account and credentials are ok. Do I need to use a token or something like that ?
I use the PokeMobBot

Thanks you

**Comment by Marsinator** [comment]
please follow the steps from https://github.com/NecronomiconCoding/NecroBot/wiki/Automatic-Locations-Sniping-Guide when setting up pokemongofeeder.

make sure discord user is your actual email used to create the discord account.

**Comment by drusty94** [comment]
I'm getting the same error. (When i use yesterday got no 'Failed to authroize' error).

**Comment by xxlovett0706** [comment]
I'm getting the same error too, why?

**Comment by health901** [comment]
I got the same error today

**Comment by slowstep** [comment]
same error，about some minute later from first run，just the channel pokesnipers which i dont have in config is working。

**Comment by txt3rob** [comment]
check your emails as it asks about the IP being authorized before it works

**Comment by drusty94** [comment]
@txt3rob don't have any email asking about it, and i think everyone here already confirmed email too.

**Comment by GoodMile** [comment]
I got the same error today,

**Comment by xYellx** [comment]
i have the same issue, i think the problem is that the system proxy is ignored.

**Comment by A-Charvin** [comment]
Same issue.

**Comment by forReason** [comment]
same here. triplechecked the mail. this morning it worked

**Comment by amlaanb** [comment]
Has anyone figured this out?

**Comment by jeffsnow88** [comment]
same issue here. e-mail is already verified. However, i tried to login directly to the website, and it cant connect also. Based on that, I guess discord have connection problems atm?

**Comment by DizzyDaft** [comment]
https://status.discordapp.com/

**Comment by Ilses** [comment]
We appear to have been setting lots of fires under Discord's servers, and have worked with staff to mitigate these issues by switching to a dedicated feed system. Please update to the latest version -- additionally, a new release should be available within the next few hours.
