### ISSUE TITLE
System.NullReferenceException & System.Runtime.CompilerServices.TaskAwaiter

### ISSUE THREAD

**Issue by azxsw** [5andr0/PogoLocationFeeder#355]
Hello, 
I am using the bot to run two account, one for red team and the other for yellow team, however the error only shows on the yellow team. I have swamp my gmail on the auth.json and yet the error only pops when i use the yellow team. I have two separate folder for each account and the config.json are almost the same. 

 
![pokemobbot](https://cloud.githubusercontent.com/assets/20988911/17620181/8148be36-6058-11e6-82d9-89aea1094891.jpg)

**Comment by ExcuseMi** [comment]
This the pogolocationfeeder github, please go over the github page of your bot.
