### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by Buron666** [5andr0/PogoLocationFeeder#36]
what the server down or i got error from 

PogoLocationFeeder is brought to you via https://github.com/5andr0/PogoLocationF
eeder
This software is 100% free and open-source.

Listening...
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.
Pokesnipers API down: The remote server returned an error: (403) Forbidden.

with All Systems Operational at https://status.discordapp.com/

**Comment by akatimka** [comment]
https://github.com/5andr0/PogoLocationFeeder/issues/77

**Comment by Ilses** [comment]
Going to close since #77 is closed -- please re-open if you're experiencing the same issue in our latest [release](https://github.com/5andr0/PogoLocationFeeder/releases)!
