### ISSUE TITLE
Doesn't relay many Discord messages (bug and fix found)

### ISSUE THREAD

**Issue by VPGH** [5andr0/PogoLocationFeeder#367]
On many occasions messages will come in but are not relayed to the bot. There are two reasons I was able to identify and fix.

These solutions are temporary fixes until more permanent ones can be done.

Issue 1: MessageParser.cs in public List<SniperInfo> parseMessage(string message)

Returns and multiple spaces break parsing.

Solution 1:
Place the following above line `            var lines = message.Split('\r', '\n');`
```
            while (message.Contains("  "))
            {
                message.Replace("  ", " ");
            }
```

Issue 2: ChannelParser.cs  in public ChannelInfo ToChannelInfo(string channelId)

channelId and channel.id compare wrong in line `if (string.Compare(channelId, channel.id) == 0)`

Solution 2: 

Comment out string.compare if statement.
```
//                    if (string.Compare(channelId, channel.id) == 0)
//                    {
                        channelInfo.server = channel.Server;
                        channelInfo.channel = channel.Name;
                        channelInfo.isValid = true;
                        return channelInfo;
//                    }
```

**Comment by ExcuseMi** [comment]
Solution 1 will break all multi line message where it has a pokemon on each line.
Solution 2 will break all channel filtering

**Comment by VPGH** [comment]
Updated solution 1, eliminating the returns isn't really needed.

Far as solution 2 goes, channel filtering doesn't work right to begin with. I already modified the discord_channels list to only use specific ones, and before my change it still skipped over them.

With my change it only uses the channels in my discord_channels file, so my conclusion is that it's broke.

**Comment by ExcuseMi** [comment]
Solution 1: Can you provide a text that doesn't work?
I've tried "     Dratini     42.326919           -83.042221     IV    91    confirmed     " in our test and it works.
https://github.com/5andr0/PogoLocationFeeder/blob/master/PogoLocationFeederTests/Tests/MessageParserTests.cs

Solution 2: Please show how it broken in with this test:
https://github.com/5andr0/PogoLocationFeeder/blob/master/PogoLocationFeederTests/Tests/ChannelParserTests.cs

There are a lot of reason why results will be filtered.
1. Pokemonfilter
2. Channel filter
3. Not found on skiplagged
4. Duplicates

And sadly, the latest version of necro had a debug in that mixed all the results of all sniping tools.

**Comment by VPGH** [comment]
It seems to be lines that have double spaces that don't filter properly. Eg: "Dratini  42.12345 -40.123456". Notice the double space between Dratina and coords. It could be that the ones I'm trying aren't found on skiplagged, but if that were the case why do they pass through when I comment out the channel filtering?

I've noticed that when the channel filter stops the message, the ID shown differs from the ID I have in the configuration. But I pulled the configuration ID directly from Discord, and I'm seeing the messages come in under that channel name.

**Comment by ExcuseMi** [comment]
1. Still can't reproduce with that example, parses fine in the tests.

2. Can you trying reconfiguring starting from this configuration file?
[discord_channels.zip](https://github.com/5andr0/PogoLocationFeeder/files/416745/discord_channels.zip)

@Ilses Are the channel Ids up to date?
Maybe their an error in the default channel configuration file.

**Comment by VPGH** [comment]
I will investigate further on my end. 

Also, the necrobot.io channels have been deleted.

**Comment by ExcuseMi** [comment]
Good point about the necro server 
@Ilses, can you remove them?

**Comment by VPGH** [comment]
I'm not able to reproduce the channelparser problem with the latest channels file. I did pull the latest discord_channels from the release before submitting a bug report as well.

I manually tested against messages containing double spaces and wasn't able to reproduce the problem. I'll watch to see if something comes by that isn't a duplicate/filtered that doesn't make it through. 

I'll follow up ASAP.

**Comment by VPGH** [comment]
Everything seems to be working. May have just been the channel list. Apologize, please close issue. Thank you!

**Comment by ExcuseMi** [comment]
No worries, thanks for the input anyway
