### ISSUE TITLE
Network Framework Incompatible

### ISSUE THREAD

**Issue by aeryl1999** [5andr0/PogoLocationFeeder#37]
It seems some versions of Windows 7 is not compatible with .Net Framework 4.6.1. Is it possible to get a release of the PogoLocationFeeder for .Net Framework 4.5.1?

**Comment by AKuHAK** [comment]
Or maybe at least it is possible to get it working with 4.6.2 as 4.6.2 is almost the same as 4.6.1

**Comment by Ilses** [comment]
This looks to be the same issue as #38 . Feel free to re-open the issue if that solution does not work for you.
