### ISSUE TITLE
"Connecting"

### ISSUE THREAD

**Issue by tr1p0z** [5andr0/PogoLocationFeeder#372]
I just updated to the last version and im getting this:
https://gyazo.com/05c498afd15e4f7e7616ec8a062cfd8b

**Comment by tr1p0z** [comment]
Okey fixed downloading lastest release!

**Comment by klykly1** [comment]
can you send me the link the latest version bro? thanks

**Comment by ExcuseMi** [comment]
Can't recommend the master version, it's very expiremental.
