### ISSUE TITLE
[Request] Auto-scrolling for the Debug Screen

### ISSUE THREAD

**Issue by HilltribeG** [5andr0/PogoLocationFeeder#376]
Debug screen could use an auto-scrolling option to stay on the newest message and also when disabled stay locked one the current position during new messages instead of automatically snapping back to the top. Would making monitoring the Debug messages easier. @tensei

**Comment by tensei** [comment]
ehh i disabled auto bc of cpu spikes

2016-08-15 4:46 GMT+02:00 HilltribeG <notifications@github.com>:
