### ISSUE TITLE
Connection lost: pogofeeder.live

### ISSUE THREAD

**Issue by nicholashew** [5andr0/PogoLocationFeeder#386]
Unable to connect to the server (master branch), below is my config.json setting

```js
{
  "Port": 16969,
  "UsePokeSnipers": true,
  "UsePokezz": true,
  "UsePokewatchers": true,
  "PokeSnipers2Exe": "",
  "RemoveAfter": 15,
  "ShowLimit": 30,
  "VerifyOnSkiplagged": true,
  "UsePokemonGoIVClub": true,
  "UseFilter": true,
  "UseGeoLocationBoundsFilter": true,
  "GeoLocationBounds": {
    "SouthWest": {
      "Latitude": 1.237759,
      "Longitude": 103.608435
    },
    "NorthEast": {
      "Latitude": 1.471575,
      "Longitude": 104.044219
    }
  },
  "AppTheme": "Dark",
  "IsServer": false,
  "IsManaged": true,
  "ServerHost": "pogofeeder.live",
  "ServerPort": 49000,
  "ShareBotCaptures": true,
  "BotWebSocketPorts": [
    14251
  ],
  "VerifiedOnly": true
}
```

**Comment by ExcuseMi** [comment]
Cloudflare acting up again. Should work now.
Are you working on filtering a certain area to catch only pokemon near the bot?
  "UseGeoLocationBoundsFilter": true,
  "GeoLocationBounds": {
    "SouthWest": {
      "Latitude": 1.237759,
      "Longitude": 103.608435
    },
    "NorthEast": {
      "Latitude": 1.471575,
      "Longitude": 104.044219
    }
  },
If so, that's pretty cool. Would love to get a PR for that.
If you wanna talk about, please join us on discord https://discord.gg/rqKvr

**Comment by nicholashew** [comment]
I am just adding a simple LatLngBounds settings to filtering the pokemon on received. You may comparing the commits to see whether the commit LGTM or not :smile: 
* [branch from v0.1.8](https://github.com/5andr0/PogoLocationFeeder/compare/67d9b95...nicholashew:filter-snipe-bounds-v0.1.8) - working
* [branch from master](https://github.com/5andr0/PogoLocationFeeder/compare/master...nicholashew:filter-snipe-bounds) - pending for test due to facing connection issue

**Comment by ExcuseMi** [comment]
I checked, You can make a PR.

**Comment by nicholashew** [comment]
For master?

**Comment by ExcuseMi** [comment]
yes or you can join the discord so we can talk https://discord.gg/rqKvr

**Comment by ExcuseMi** [comment]
You should be able to test this with the server atm
