### ISSUE TITLE
Fix pokewatchers pls

### ISSUE THREAD

**Issue by Naprosnia** [5andr0/PogoLocationFeeder#391]
Pokewatchers changed their api.

**Comment by ExcuseMi** [comment]
Sadly, their new API is hidden behind a javascript redirect.
Meaning it only works for requests that can handle javascript, aka browsers.
Not sure if they did this intentionally. 

I'll create a dirty workaround for now.

**Comment by Koolsami7** [comment]
I disabled the javascript detection, you should be fine now.

**Comment by ExcuseMi** [comment]
Great! Updated the code on the master, I guess this also fixes the previous release.

**Comment by ExcuseMi** [comment]
It seems broken again now. Timeouts, even on the site.

**Comment by Koolsami7** [comment]
It's up now, our server host had an issue with IP allocation.. So we were
down for a little bit today.. But we're up now!
