### ISSUE TITLE
bad translation of coordinates

### ISSUE THREAD

**Issue by harmmm** [5andr0/PogoLocationFeeder#4]
Hi,

Somehow catching the coordinates does not go 100% right at my side yet.

`Channel: rare_pokemon ID: Lickitung, Lat:34065686225826, Lng:-11820053040781, IV:0`
`Channel: rare_pokemon ID: Ivysaur, Lat:-3,38858475330327E+15, Lng:1,51137451529503E+16, IV:0`
`Channel: rare_pokemon ID: Dewgong, Lat:51512530862528, Lng:-11270292504326, IV:0`
`Channel: rare_pokemon ID: Lickitung, Lat:20848397236819, Lng:-15650727538931, IV:0`

which at the rare_pokemon channel is:

`[14:06] Ludicrous Beach: [13:6:34] Lickitung | 2m 39s | 34.065686225826,-118.20053040781`
`[14:06] InfinityISB4CK: Ivysaur 30s -33.88584753303274,151.13745152950287`
`[14:07] Ludicrous Beach: [13:7:55] Dewgong | 13m 0s | 51.512530862528,-0.11270292504326`
`[14:09] Ludicrous Beach: [13:9:27] Lickitung | 5m 20s | 20.848397236819,-156.50727538931`

result in necrobot client:

`[14:13:28] (INFO) [Sniper] Scanning for Snipeable Pokemon at 47515011312869,19079546013186...`
`[14:13:33] (INFO) [Sniper] Scanning for Snipeable Pokemon at 34013929574941,-11848032881899...`
`[14:13:39] (INFO) [Sniper] Scanning for Snipeable Pokemon at -339197578013,151144188357...`

**Comment by 5andr0** [comment]
https://github.com/5andr0/PogoLocationFeeder/commit/5e3b4c8f5ee3975da10726b9c0d750922db878cb
