### ISSUE TITLE
Failed to authroize  By Discord.Net.TimeoutException

### ISSUE THREAD

**Issue by squall1009** [5andr0/PogoLocationFeeder#40]
Failed to authroize Discord user! Check your config.json and try again.
Caught exception: Discord.Net.TimeoutException: An operation has timed out.

**Comment by xSINIQx** [comment]
probably because of this:
[https://cdn.discordapp.com/attachments/206073715170082818/209368312386158592/CsldaRG.png](url)

**Comment by degree8th** [comment]
probably because you use proxy?

**Comment by Ilses** [comment]
We've migrated to a feed system by request of Discord staff. Please upgrade to the latest version. Additionally, an improved release should be available in a few hours.
