### ISSUE TITLE
PokeZZ spamming pokemon

### ISSUE THREAD

**Issue by VBQL** [5andr0/PogoLocationFeeder#408]
Any pokemon I put in the filter instantly comes up with a page full of results from PokeZZ, even the legendaries, using this with NecroBot, and nothing is found when picked up.

**Comment by cswxin** [comment]
same here

**Comment by cswxin** [comment]
same here from yesterday

**Comment by ExcuseMi** [comment]
Disable skiplagged

**Comment by alexbaas** [comment]
@ExcuseMi Why is Skiplagged doing this? Are they sending random info or something??
