### ISSUE TITLE
Failed to get discord details

### ISSUE THREAD

**Issue by am3yar0ra** [5andr0/PogoLocationFeeder#41]
![image](https://cloud.githubusercontent.com/assets/1933816/17289112/d1eb8ee2-57f5-11e6-98aa-0c057dc910d5.png)

After updating it to the lastest one i am getting this error again and again. A few times it did load some coords and then again the same error. Any fix ?

**Comment by forReason** [comment]
same here

**Comment by Revoss** [comment]
same here

**Comment by omar972** [comment]
Still using the previous version, getting same error. Probably a problem with Discord's servers.

**Comment by omar972** [comment]
https://status.discordapp.com/
Servers are taking fire from all the Pokemon Go servers, not a problem with PogoFeeder and the devs can't do anything about it.

**Comment by Ilses** [comment]
Actually, it turns out we might have been responsible for some of that fire. We worked with Discord staff to migrate PogoLocationFeeder to a dedicated Discord feed system, so please update to the latest version. We should also have an improved release available in another few hours.
