### ISSUE TITLE
Not filtering

### ISSUE THREAD

**Issue by kamstar** [5andr0/PogoLocationFeeder#420]
Hi,
Since the new update last night it won't filter the rare pokemon. I mean i'm getting zubat's and all sorts in the list. Pokemon to feed just shows the rare ones are only selected.
Any ideas?

Thanks
![pok1](https://cloud.githubusercontent.com/assets/21158120/18027036/47bbf558-6c50-11e6-8a9c-97ecf1725697.PNG)
![pok2](https://cloud.githubusercontent.com/assets/21158120/18027037/4ffabcc2-6c50-11e6-9990-3176a55ed76e.PNG)

**Comment by kamstar** [comment]
Sorry just to add i'm using 0.1.9.0. 
Reverting back to the old one works fine

**Comment by ExcuseMi** [comment]
is the useFilter setting on ?

**Comment by kamstar** [comment]
No it wasnt on by default lol. Lol sorry for being a lazy ass. Thanks! its sorted
