### ISSUE TITLE
Serverport

### ISSUE THREAD

**Issue by evetaku** [5andr0/PogoLocationFeeder#425]
serverport its true 16969 or 49000 ? but in GUI 16969 and config 49000. so implementation in necro SnipeLocationServerPort": 16969 or 49000 ?

**Comment by ExcuseMi** [comment]
"SnipeLocationServerPort": 16969 to connect to the bot.

**Comment by evetaku** [comment]
i dont know why, when in v1.8 sniping working very well and fastrespon, but after update v1.9 sniping very slowly in bot.example when use v1.8 in bot set
"UseSnipeLocationServer": true,
"SnipeLocationServer": "localhost",
"SnipeLocationServerPort": 16969,
"MinDelayBetweenSnipes": 10000
its oke keep fastrespon,but after v1.9 sniping very slowly and never sniping.
what's IsServer in pogo ? set true or false ?

**Comment by ExcuseMi** [comment]
It means other PogoLocationFeeders can connect to yours and get coordinates. It also means no bots can connect to it.

**Comment by evetaku** [comment]
so IsServer set in false if i want use in bot ?
and Botinwebsocketport what's ? and in bot set false or true ?

**Comment by ExcuseMi** [comment]
IsServer is false (should be like that for normal users)
Please take a look at the documentation for this release.
https://github.com/5andr0/PogoLocationFeeder/releases

**Comment by evetaku** [comment]
@ExcuseMi  thanks you
