### ISSUE TITLE
How to extract data with PHP

### ISSUE THREAD

**Issue by Anderuimm** [5andr0/PogoLocationFeeder#426]
I wish to get all Pokemon locations on a live map, then how can I get the PogoLocationFeeder info with PHP to insert into my database? Or there is a way to insert the Pokémon info directly on a MySQL Database?

**Comment by ruchern** [comment]
Get XAMPP. Start all the server, then go to `localhost/phpmyadmin`

Then you should see your database.

**Comment by Anderuimm** [comment]
I believe that was not understood by @ruchern  then I'll try to explain it with more details: I want to install PogoLocationFeeder on my server and, with a cronjob or scheduled task, start a PHP script or something similar to capture the PogoLocationFeeder data and insert them into a database. I've tried to do it with the logfile that is generated by software but , besides being far from a good practice, it is a rough adaptation of functionality.

I know that other software ( bots ) do the same, I just like to know how to adapt to PHP and what parameters should I use.

**Comment by ExcuseMi** [comment]
Start a pogofeeder client and listen to the socket in PHP.
Example: http://stackoverflow.com/questions/12999900/php-socket-listening-loop
Listen to the port property in the settings.

You start receiving json objects in the following format.
        [JsonProperty("ExpirationTimestamp")]
        public DateTime ExpirationTimestamp { get; set; }
        [JsonProperty("Latitude")]
        public double Latitude { get; set; }
        [JsonProperty("Longitude")]
        public double Longitude { get; set; }
        [JsonProperty("Id")]
        public PokemonId Id { get; set; } = PokemonId.Missingno;
        [JsonProperty("IV")]
        public double IV { get; set; }
        [JsonProperty("Move1")]
        public PokemonMove Move1 { get; set; }
        [JsonProperty("Move2")]
        public PokemonMove Move2 { get; set; }

To help you some, here is the pokemonId enum
http://pastebin.com/CnEkGEmh
and the PokemonMove enum
http://pastebin.com/JtgyhpS9

Please send us a link if you get it working.

**Comment by Anderuimm** [comment]
TYVM @ExcuseMi
