### ISSUE TITLE
Just a reminder, I'm using release v0.0.1, discord is available.

### ISSUE THREAD

**Issue by windyair** [5andr0/PogoLocationFeeder#43]
Try release v0.0.1, if you cannot coonect to discord

**Comment by Ilses** [comment]
We are trying to migrate to a separate, dedicated feed because we were causing traffic problems for Discord. To that end, we would appreciate if users could update versions, and we will be pushing many new features in the next few days.

**Comment by Ilses** [comment]
In the past few days, we've come a long way since 0.0.1 -- I will be closing this and advocating downloading our latest [release](https://github.com/5andr0/PogoLocationFeeder/releases)!
