### ISSUE TITLE
Fatal Error at start!

### ISSUE THREAD

**Issue by foaryon** [5andr0/PogoLocationFeeder#430]
Feeder brings this fatal error now at every start(v1.10)
![unbenannt](https://cloud.githubusercontent.com/assets/20794218/18080401/c170e006-6e95-11e6-9fe9-0ba50421ad20.PNG)

**Comment by sp7759** [comment]
i am getting this is well

**Comment by k0lev** [comment]
same

**Comment by ExcuseMi** [comment]
Is it fixed now?

**Comment by ExcuseMi** [comment]
I had updated the version to try to fix the upgrader. Reverted back the changes now. Works again for me now.

**Comment by foaryon** [comment]
**Fixed for now...tested in severals times, no more fatal error with v.1.1.0 so you can use it all now!!!**
