### ISSUE TITLE
[Bug] Sorting in GUI not working

### ISSUE THREAD

**Issue by iwean** [5andr0/PogoLocationFeeder#431]
![screenshot_153](https://cloud.githubusercontent.com/assets/4365551/18082710/3e864822-6eca-11e6-9725-32348c3cd440.jpg)

**Comment by ExcuseMi** [comment]
Not specific to this version, related to #221
I might take a look

**Comment by foaryon** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/20794218/18184007/3faecce6-7097-11e6-9e27-8a6e55d121c4.png)

happens to me aswell
