### ISSUE TITLE
Cannot logging on server: pokefeeder.live

### ISSUE THREAD

**Issue by nickvnn** [5andr0/PogoLocationFeeder#433]
Hey bruh,

After me update PogoLocationFeeder to v.0.1.10, it's cannot logging on server: pokefeeder.live.
Please, help and thanks to advice

![image](https://cloud.githubusercontent.com/assets/21334078/18084856/01ccf044-6ed3-11e6-86b6-38a46a3b6f0c.png)

**Comment by ExcuseMi** [comment]
Logfile?
Can you ping pokefeeder.live?

**Comment by nickvnn** [comment]
Ok, tks for answer. I  figured it out. Seem to when i change my DNS it's can't logging on pokefeeder server.

**Comment by ExcuseMi** [comment]
ipconfig /flushdns might help in the future.

**Comment by Jay2091** [comment]
> ExcuseMi commented 9 days ago
Logfile?
Can you ping pokefeeder.live?


i cant ping pokefeeder.live
