### ISSUE TITLE
feeder errors out if Farfetch'd is in the list for pokesnipers.com

### ISSUE THREAD

**Issue by Afraidium** [5andr0/PogoLocationFeeder#44]
Pokesnipers API down: Requested value 'Farfetch'd' was not found.
I'm not sure if this also happens with Mr. Mime. Special characters not being escaped?

**Comment by ExcuseMi** [comment]
Are you on the latest version?
This was already fixed.

**Comment by ExcuseMi** [comment]
This has already been fixed:
![](https://cloud.githubusercontent.com/assets/16978537/17312939/723d93fc-5857-11e6-86f7-d80df8b7a461.png)
