### ISSUE TITLE
show MinimumIV pokemons, but can't snipe?

### ISSUE THREAD

**Issue by tim2003251** [5andr0/PogoLocationFeeder#442]
When I set "PokemonNotInFilterMinimumIV": 90.0,
and it can show all IV higher than 90,
but it won't snipe pokemons not in my filter.

I think the reason is that those pokemons shown on list aren't set in Necro's "Pokemon" ?
Or those just are wrong information, so it will not snipe.

**Comment by tim2003251** [comment]
Then I try to add all pokemons in Necro's "Pokemon",
the snipe is working, but those are low IV, not 90.

**Comment by ExcuseMi** [comment]
Are they 90 in pogofeeder?

**Comment by tim2003251** [comment]
Yes, pogofeeder only shows higher than 90.
But it also snipe others not in pogofeeder.

I assume a situation:

in pogofeeder:
set "PokemonNotInFilterMinimumIV": 90.0,
"MinimumIV": 0.0,
filter: ["Dragonite"]

in NECRO:
set "Pokemon" : ["Dragonite"]
---------------------
result:
(1)pogofeeder shows any IV dragonite and others higher than 90.
(2)NECRO only snipes dragonite, not all shown in pogofeeder.


Do I misunderstand the function?
I guess it snipes all shown in pogofeeder.
That is, it will snipe "any IV dragonite" + "any higher than 90 not in filter" (e.g. IV:90 Magikarp, IV:95 Eevee, etc.)

**Comment by tim2003251** [comment]
![default](https://cloud.githubusercontent.com/assets/21376332/18204264/5d231680-714e-11e6-8a2c-1fb73acfa98d.JPG)


Red line is not in my filter and more than 90.
But it only can snipe blue line.
How can I snipe all pokemons shown on pogofeeder list

**Comment by ExcuseMi** [comment]
Does your bot/pokesniper2 have a snipeable pokemon list? Maybe these pokemon aren't allowed to be sniped?

**Comment by tim2003251** [comment]
"Pokemon": [
      "growlithe",
      "arcanine",
      "slowbro",
      "gyarados",
      "lapras",
      "vaporeon",
      "snorlax",
      "jolteon",
      "flareon",
      "dratini",
      "dragonair",
      "exeggutor",
      "dragonite"
    ]

Actually, I really don't know showing "PokemonNotInFilterMinimumIV" is for what ?
When using bot and snipe other high IV manually, or automatically ?

**Comment by ExcuseMi** [comment]
Anything that shows up in the list, will be sent to the bot. Then the bot decides what to do with it according to his own properties.

**Comment by tim2003251** [comment]
So how can i fix my bot setting in that situation mentioned above ?
Should I update my bot to the latest version?

**Comment by cl3537git** [comment]
Tim ExcuseMi isn't Necrobot support. Go get help there if you need it.
In Necrobot config:

 "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "machamp",
      "golem",
      "exeggutor",
      "lapras",
      "vaporeon",
      "snorlax",
      "dragonite",
      "dragonair",
      "dratini",
      "golem",
      "geodude",
      "machop",
      "machamp",
      "machoke",
      "graveler"
    ]

You can filter which ones display in  PogoFeeder and then which ones the bot will try to catch in  Necrobot config both work.

**Comment by tim2003251** [comment]
_tim2003251 commented 2 days ago
Then I try to add all pokemons in Necro's "Pokemon",
the snipe is working, but those are low IV, not 90._

I had already tried this way.
The bot will scan all pokemons from pokezz, pokesnipers, etc.

**Comment by cl3537git** [comment]
If you are sniping PokeZZ from the Pogofeeder it will shows as (localhost), if you are sniping directly from Pokezz it will say Pokezz.


  "SnipeConfig": {
    "UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    **"GetSniperInfoFromPokezz": true,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": false,**
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 5000,
    "SnipingScanOffset": 0.05,
    "SnipeAtPokestops": true,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": false,
    "SnipeRestSeconds": 10,
    "SnipeCountLimit": 200
  },

Look at the bolded lines in Necorbot config and set them to false if you only want to use Pogofeeder and its filters to snipe.

Alternatively you can set UseTransferIVtoSnipe and limit sniping to a certain IV number.

**Comment by tim2003251** [comment]
Thank you, cl3537git !
I think the way is feasible.
