### ISSUE TITLE
Bug "IV:0"

### ISSUE THREAD

**Issue by kaeld59** [5andr0/PogoLocationFeeder#45]
Seems there are error with IV. It's always said "IV:0" when pokemon has been located.

![capture](https://cloud.githubusercontent.com/assets/20775729/17298790/bb4ca106-580b-11e6-8127-6fd3aa936e44.PNG)

**Comment by kaeld59** [comment]
Pogolocationfeeder configuration:

{
  "ServerChannels": [
    "coord-bot",
    "coords_bot",
    "coordsbots",
    "90_plus_iv",
    "90plus_ivonly",
    "rare_spottings",
    "high_iv_pokemon",
    "rare_pokemon",
    "high_iv"
  ],
  "DiscordToken": "",
  "Port": 16969,
  "useToken": false,
  "DiscordUser": "mymail",
  "DiscordPassword": "mypassword",
  "usePokeSnipers": true
}

**Comment by ExcuseMi** [comment]
The pokemon locations provided by pokesnipers.com don't contain any IV information.
That's why it's 0 for pokesnipers.

**Comment by Ilses** [comment]
'0' is the default IV for entries we are not able to parse. This includes multi-line entries.

**Comment by kaeld59** [comment]
Ok, i understand better now. Thanks for the replies.
