### ISSUE TITLE
Connecting to server

### ISSUE THREAD

**Issue by xrfez** [5andr0/PogoLocationFeeder#456]
//Is the server having issues?  6:28pm Pacific Time

**Comment by BlackStarDark** [comment]
Probably.. I'm having your same issue ._.

**Comment by BlackStarDark** [comment]
did a ping to pokefeeder.live and it seems to be down .. 100% Packets lost.

**Comment by xrfez** [comment]
Cool.  Dropped a note on Discord and those guys were saying the server is not maintained by the dev.  and that guy isnt available...  Wait it out

**Comment by iwean** [comment]
change to connect to discord server

  "IsManaged": false,

**Comment by nhhoang667** [comment]
@iwean Thank you! It's fixed.

**Comment by Jay2091** [comment]
didnt work for me.. can someone help me with mine 
![untitled](https://cloud.githubusercontent.com/assets/22068006/18337014/7d8fb822-75bf-11e6-98f5-061c05c5383d.png)

**Comment by henrysheva** [comment]
sorry iwean i don't get what u type about. can u make it detail? cause i'm not programmer here. thx

**Comment by henrysheva** [comment]
![1](https://cloud.githubusercontent.com/assets/22068733/18338150/e884afb0-75c0-11e6-864e-26679335105e.jpg)
 no idea where to make that iwean

**Comment by DSanHao** [comment]
Used this setting and currently worked night now 
> 
{
  "Port": 16969,
  "UsePokeSnipers": true,
  "UsePokezz": true,
  "UsePokewatchers": false,
  "PokeSnipers2Exe": "",
  "RemoveAfter": 7,
  "ShowLimit": 30,
  "VerifyOnSkiplagged": false,
  "UsePokemonGoIVClub": true,
  "UsePokeSnipe": true,
  "UseFilter": true,
  "UseGeoLocationBoundsFilter": false,
  "GeoLocationBounds": {
    "SouthWest": {
      "Latitude": 40.744627259246641,
      "Longitude": -74.006222741943361
    },
    "NorthEast": {
      "Latitude": 40.816119123701981,
      "Longitude": -73.903569238525392
    }
  },
  "AppTheme": "Dark",
  "IsServer": false,
  "IsManaged": false,
  "ServerHost": "pokefeeder.live",
  "ServerPort": 49000,
  "OutgoingServerPort": 49000,
  "ShareBotCaptures": false,
  "BotWebSocketPorts": [
    14251
  ],
  "VerifiedOnly": false,
  "MinimumIV": 0.0
}
> 
![untitled](https://cloud.githubusercontent.com/assets/20865552/18338444/1fdd272e-75c3-11e6-8861-ae79af7f2c0c.png)

**Comment by mearymary** [comment]
latest feeder access "http://pogo-feed.mmoex.com/messages". so not work feeder.

**Comment by henrysheva** [comment]
mearymary..where i can edit? thx

**Comment by kaiserblue** [comment]
The config posted by DSanHao works for me. Thanks man!

**Comment by henrysheva** [comment]
where to edit ?

**Comment by tngs01** [comment]
not working for me :/

**Comment by GioMarraschi** [comment]
The 0.1.6 version is still working but only get pokemons from pokesnipers.com .. and don't show IV's but still better than nothing!

**Comment by xrfez** [comment]
yeah you can set it to pull discord channels but do any of you get IV stats in the return?

**Comment by kaiserblue** [comment]
Nope not getting any iv stats not until this will be fixed by the moderator. @henrysheva you can edit it via the config within the same folder of the pogo location feeder.

**Comment by henrysheva** [comment]
thx..i did the edit but can't see any live target...i mean every links i snipped the pokemon already not there..the connection with those links not really worked..the only way until this thing fixed is directly open pokesniper.com and snipping from there

**Comment by kaiserblue** [comment]
That's normal since all coordinates are not verified. It still works for me unless you do manual sniping.

**Comment by henrysheva** [comment]
poke

**Comment by manrox** [comment]
> 

Used this setting and currently working night now

    {
    "Port": 16969,
    "UsePokeSnipers": true,
    "UsePokezz": true,
    "UsePokewatchers": false,
    "PokeSnipers2Exe": "",
    "RemoveAfter": 7,
    "ShowLimit": 30,
    "VerifyOnSkiplagged": false,
    "UsePokemonGoIVClub": true,
    "UsePokeSnipe": true,
    "UseFilter": true,
    "UseGeoLocationBoundsFilter": false,
    "GeoLocationBounds": {
    "SouthWest": {
    "Latitude": 40.744627259246641,
    "Longitude": -74.006222741943361
    },
    "NorthEast": {
    "Latitude": 40.816119123701981,
    "Longitude": -73.903569238525392
    }
    },
    "AppTheme": "Dark",
    "IsServer": false,
    "IsManaged": false,
    "ServerHost": "pokefeeder.live",
    "ServerPort": 49000,
    "OutgoingServerPort": 49000,
    "ShareBotCaptures": false,
    "BotWebSocketPorts": [
    14251
    ],
    "VerifiedOnly": false,
    "MinimumIV": 0.0
    }

    untitled

i had tried it,but pogo snipe others coordinate which not follow the coordinate snipe pokemon location
