### ISSUE TITLE
How do I make it to keep pidgeys, etc and after 90% full bag evolve?

### ISSUE THREAD

**Issue by Revoss** [5andr0/PogoLocationFeeder#47]
I have 
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"

"EvolveKeptPokemonsAtStorageUsagePercentage": 0.9,

Should I add these pokemon into the "PokemonsNotToTransfer": ?

Thanks

**Comment by adde88** [comment]
That question is not relevant to PogoLocationFeeder.
It's probably better suited inside the repo. for the Pokemon Go bot you are using. :)

**Comment by Ilses** [comment]
Hey -- this is a client-side issue. Check with the maintainers of your particular Pokemon Go bot for advice on configuration options.
