### ISSUE TITLE
valid discord creds but PogoLocationFeeder shows no output 

### ISSUE THREAD

**Issue by blackwat3r** [5andr0/PogoLocationFeeder#49]
discord creds are valid, i can log in and view/talk in the channels however PogoLocationFeeder parses 0 data from any of the channels in the config

G:\POGO\PogoLocationFeeder-Release-V0.0.2.1
λ PogoLocationFeeder.exe
Listening...
New connection from 127.0.0.1:4021

nothing shows up besides this.
the pokesniper api is working but not discord for some reason.
ive had this same issue with the other pogolocationfeeder releases as well

**Comment by Mikey9191** [comment]
Same here, some people are saying the servers are down? not sure

**Comment by blackwat3r** [comment]
nothing to do with servers being down. its been doing this since day 1

**Comment by ctluciani** [comment]
If day 1 was yesterday, it was working. Not today though.

**Comment by Ilses** [comment]
Hey all -- we no longer require Discord authentication (see wiki for details). Make sure to grab the latest [release](https://github.com/5andr0/PogoLocationFeeder/releases)!
