### ISSUE TITLE
Is it normal?

### ISSUE THREAD

**Issue by miracho** [5andr0/PogoLocationFeeder#52]
im updated pogolocationfeeder in git shell.

and...

> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:
> Raw message:

**Comment by Ilses** [comment]
We shifted from channels to a feed -- try the latest master, or the next release which should be arriving shortly.
