### ISSUE TITLE
Showing ID: Missingno instead of poke's real name?

### ISSUE THREAD

**Issue by alonexquan** [5andr0/PogoLocationFeeder#59]
It sometimes shows the ID of pokemon as "Missingno"  (50% of the time), any idea why?

Thank you for your guys' work!

**Comment by omar972** [comment]
"Missingno" is PogoFeeder's way to tell you that the person who posted the coordinates for this pokemon, misspelled it's name. For example if someone says in discord "snlrax LATITUDE,LONGITUDE IV:90" PogoFeeder will says "Missingno LATITUDE,LONGITUDE IV:90"

**Comment by Ilses** [comment]
At some point, I added an explanation on MissingNo to the wiki/FAQ page, but it was likely after this question.

Closing this because @omar972 beat me to it -- Thanks!
