### ISSUE TITLE
Necrobot overwrites cfg

### ISSUE THREAD

**Issue by painhardcore** [5andr0/PogoLocationFeeder#6]
Necrobot latest version, i adding in conf file
 "SnipeAtPokestops": true,
  "MinPokeballsToSnipe": 0,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "UseSnipeLocationServer": true,
  "UseTransferIVForSnipe": false,
  "MinDelayBetweenSnipes": 5000,

and after Necrobot starts its deletes this lines in conf

**Comment by romkazor** [comment]
Confirm

**Comment by Ilses** [comment]
The lines shouldn't be deleted. They may be rearranged/relocated, however.. Can you make sure this isn't the case?

**Comment by romkazor** [comment]
But it deleted everytime when start NecroBot.exe
I used original bot 0.3.3 and bumb verison bot 0.3.2 (compiled by ms visual) from this repo

**Comment by Ilses** [comment]
The only reason the lines would vanish is if your NecroBot is outdated. Can you check using the latest master be2f597f ?

**Comment by painhardcore** [comment]
oooh i've been using compiled version and when i  build from source  - i see this parameters in default config

**Comment by romkazor** [comment]
be2f597f version when build from source got error

**Comment by skupfer** [comment]
Build from source, start necrobot.exe, edit your config. This is not PogoLocationFeeder related, wrong repo guys.
