### ISSUE TITLE
No discord channels working 

### ISSUE THREAD

**Issue by dragobite** [5andr0/PogoLocationFeeder#63]
I`m only getting listings from pokesniper, the other channels are not working for me anyone knows why?

This is my config: {
  "ServerChannels": [
    "sniping",
    "high_iv_pokemon",
    "rare_pokemon",
    "90_plus_iv",
    "coordsbots",
    "rare_spottings",
    "90plus_ivonly",
    "coordsbot",
    "rare_spotting",
    "90_plus_iv",
    "coord-bot",
    "rare_pokemon"
  ],
  "DiscordToken": "",
  "Port": 16969,
  "useToken": false,
  "DiscordUser": "myemail",
  "DiscordPassword": "mypassword",
  "usePokeSnipers": true
}

**Comment by omar972** [comment]
You're using an outdated version, update.

**Comment by dragobite** [comment]
Ok, thank you, I`ve updated, now i`m getting this :PogoLocationFeeder is brought to you via https://github.com/5andr0/PogoLocationFeeder/wiki
This software is 100% free and open-source.

Connecting to feeder service pogo-feed.mmoex.com
Connection issues. Retrying...
Connection established. Waiting for data...
Connection issues. Retrying...
Exception: Newtonsoft.Json.JsonSerializationException: Error converting value 15 to type 'PogoLocationFeeder.DiscordWebReader+DiscordMessage'. Path '', line 1, position 2. ---> System.ArgumentException: Could not cast or convert from System.Int64 to PogoLocationFeeder.DiscordWebReader+DiscordMessage.
   bei Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   bei Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   bei PogoLocationFeeder.Program.<>c__DisplayClass15_0.<<pollDiscordFeed>b__0>d.MoveNext() in D:\home\app\pogo\PogoLocationFeeder\PogoLocationFeeder\Program.cs:Zeile 197.

**Comment by Ilses** [comment]
Yep, new version uses a feed instead of channels (by direct request from Discord staff).
