### ISSUE TITLE
[Question] How to get the ID for a discord channel for discord_channels.json?

### ISSUE THREAD

**Issue by omar972** [5andr0/PogoLocationFeeder#64]
Example:
     "id": "209314780870213633",
    "Server": "Necrobot.io",
    "Name": "plus_90_iv"
Where to get that number?

**Comment by xxlovett0706** [comment]
I want to know too, I have same question

**Comment by Skullmonkey** [comment]
Settings > Appearance > Check developer mode
Right click channel name >Copy ID

But I have a few custom ones and they are not showing up for me. Maybe because the account the bot is using is not in the channel/server?

**Comment by FeiFogota** [comment]
Browser address bar

**Comment by Marsinator** [comment]
https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-server-ID-

**Comment by omar972** [comment]
Skullmonkey's suggestion works.

**Comment by Tr6nt0** [comment]
But this does not work forme because my Discordwas disabled. Is there a way I could mine my id from my account?

**Comment by zveinn** [comment]
The developer mode setting is now located in the "Advanced" settings menu
