### ISSUE TITLE
no discord account needed anymore?

### ISSUE THREAD

**Issue by Zerotask** [5andr0/PogoLocationFeeder#66]
Is it right that you don't need a discord account now? And where to get the the "Id"? Couldn't find it at discordapp.com

Compared to a version of yesterday it is very slow / finds not much Pokemon.

**Comment by Ilses** [comment]
Yep -- no discord account is needed. We worked with Discord staff to migrate to a dedicated feed so we stop crashing their servers. The newest release should speed things up considerably, and a slick GUI is also available ^^;
