### ISSUE TITLE
Many "Connection Issues" showing up

### ISSUE THREAD

**Issue by jarsever** [5andr0/PogoLocationFeeder#67]
I don't know if this is an issue.  I downloaded the latest and since I can't use my own account I have to rely on the program but the program seems to be having issues.
```
Connecting to feeder service pogo-feed.mmoex.com
Connection issues. Retrying...
Connection established. Waiting for data...
Connection issues. Retrying...
Server: Necrobot.io, Channel: sniping ID: Missingno, Lat:37.6496538037648, Lng:-122.081214
571097, IV:0
No new pokemon on PokeSnipers
No new pokemon on PokeSnipers
No new pokemon on PokeSnipers
New connection from 127.0.0.1:50540
Experiencing connection issues. Throttling...
No new pokemon on PokeSnipers
Connection established. Waiting for data...
Connection issues. Retrying...
No new pokemon on PokeSnipers
No new pokemon on PokeSnipers
```

Is there any way you can allow us to use our own account?

**Comment by Ilses** [comment]
Hey -- we can't support user accounts at this time (we were contacted by Discord's CTO -- see wiki for details). Could you try upgrading to the latest [release](https://github.com/5andr0/PogoLocationFeeder/releases) (v0.1.3)? It should handle unstable connections better.

**Comment by Ilses** [comment]
(closing this since it relates to a previous release -- please re-open if you're still experiencing issues!)
