### ISSUE TITLE
NecroBot (be2f597) won't get fed

### ISSUE THREAD

**Issue by skupfer** [5andr0/PogoLocationFeeder#7]
Using the most recent commit be2f597 because it incorporates the 30minutes crashfix, the bot won't get fed properly.

Not sure whether it's Necro or Feeder related, but it seems several internationalization commits were made, maybe that messed up your code or the way data is read from your Feeder.

Coords are being displayed as this:

Channel: rare_pokemon ID: Magneton, Lat:41,9768897852, Lng:-87,6686313758, IV:0
Channel: rare_spottings ID: Arcanine, Lat:-33,918985126, Lng:150,975329032, IV:0
Channel: rare_pokemon ID: Missingno, Lat:-33,918985126, Lng:150,975329032, IV:0
Channel: 90plus_ivonly ID: Lapras, Lat:51,5102916301503, Lng:-0,0355768203735352, IV:91,806
Channel: rare_spottings ID: Snorlax, Lat:-33,9288514758, Lng:150,858527966, IV:0

So the problematic commata-variant is being used I think. Wasn't a problem with your fork, but is one with NecroBots.

**Comment by Ilses** [comment]
Did you get the client connection message when you started up NecroBot?

**Comment by shabbz** [comment]
im having the same issue. Both apps running fine however NecroBot just wont snipe anything (yes i have set the config to snipe)

**Comment by shabbz** [comment]
"SnipeAtPokestops": true,
  "MinPokeballsToSnipe": 0,
  "SnipeLocationServer": "rare_pokemon",
  "SnipeLocationServerPort": 16969,
  "UseSnipeLocationServer": true,
  "UseTransferIVForSnipe": true,
  "MinDelayBetweenSnipes": 500,

**Comment by skupfer** [comment]
Yes, it printed that given information "New connection from 127.0.0.1:2224"

Doesn't matter whether I use one bot instance or 9 ;)

**Comment by shabbz** [comment]
i dont even get a recognistion of connection from the feeder

**Comment by skupfer** [comment]
@shabbz the SnipeLocationServer must be "localhost" or an actual IP adress. You entered a discord channel here, wrong config.

**Comment by shabbz** [comment]
duuhhh thanks bro

**Comment by shabbz** [comment]
hopefully it works now

**Comment by nenko91** [comment]
Guys, how did you get those stuff to appear in the necrobot config file?
"MinPokeballsToSnipe": 0,
"SnipeLocationServer": "rare_pokemon",
"SnipeLocationServerPort": 16969,
"UseSnipeLocationServer": true,
"UseTransferIVForSnipe": true,
"MinDelayBetweenSnipes": 500,

**Comment by skupfer** [comment]
@nenko91 update to the most recent version ... could you please NOT use a real issue for questions? This is the wrong repository, too.

**Comment by shabbz** [comment]
bot running for 10mins, 15 pokestops still no snipe (even though now the feeder recognised the bot)

**Comment by shabbz** [comment]
@skupfer i hope i can ask questions here as this is a similar issue?

**Comment by skupfer** [comment]
Seems like its the same issue.

May I ask @shabbz, are you using a selfcompile version at most recent commit (named above)?

**Comment by shabbz** [comment]
no i am using the release, should i try with the selfcompile version and get back to you?

**Comment by Ilses** [comment]
I'm using the compiled master. @skupfer -- want to PM me on discord if you're still having problems?

**Comment by shabbz** [comment]
however with Necro i am using the latest selfcompile version available

**Comment by skupfer** [comment]
It's working for you @Ilses? Then yes, maybe we can talk about it, would be great.

I mean, wait. I am confused. The bots are running for more than 1 hour now, all of a sudden all started to snipe now, simultaneously oO

**Comment by skupfer** [comment]
Alright, sniper is working now!

If you set "UseTransferIVForSnipe": true and almost all data the Feeder collects doesn't show an IV (IV: 0) he WONT snipe at all. Sure that, stupid me!

Set "UseTransferIVForSnipe": false and watch it Sniping!
