### ISSUE TITLE
Not working with ie proxy

### ISSUE THREAD

**Issue by degree8th** [5andr0/PogoLocationFeeder#70]
With PogoLocationFeeder v0.0.2.1 it says
`No new pokemon on PokeSnipers`
`Failed to authroize Discord user! Check your config.json and try again.`

With PogoLocationFeeder-Release-V0.1.1-Hotfix it crashes.
`Connection issues. Retrying...`
`Exception: Newtonsoft.Json.JsonSerializationException: Error converting value 66 to type 'PogoLocationFeeder.DiscordWebReader+DiscordMessage'. Path '', line 1, position 2. ---> System.ArgumentException: Could not cast or convert from System.Int64 to PogoLocationFeeder.DiscordWebReader+DiscordMessage.
   в Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   в Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- Конец трассировки внутреннего стека исключений ---
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   в PogoLocationFeeder.Program.<>c__DisplayClass15_0.<<pollDiscordFeed>b__0>d.MoveNext() в D:\home\app\pogo\PogoLocationFeeder\PogoLocationFeeder\Program.cs:строка 197`

**Comment by Ilses** [comment]
Hey -- could you try the latest v0.1.3 release and re-open this if you're still experiencing issues?
