### ISSUE TITLE
PokeMobBot keeps Skipping the Sniped Pokemon

### ISSUE THREAD

**Issue by Gardagger** [5andr0/PogoLocationFeeder#72]
Solved!

**Comment by incizzle** [comment]
same thing for me bro :(

**Comment by Gardagger** [comment]
Atleast im not the only one but ive missed out on some pretty sweet IV:100's cuz it just moves on

**Comment by jinkawasaki333** [comment]
It could mean that the coordinate is fake.

**Comment by Gardagger** [comment]
oh ok, bunch of Fakers man xD

**Comment by Gardagger** [comment]
tell me its a f*cking Gyarados IV 100 like freak off xD
