### ISSUE TITLE
Can You Guys Add UseIgnorePokeStops because i think its skipping pokemon because of Pokestops

### ISSUE THREAD

**Issue by Gardagger** [5andr0/PogoLocationFeeder#73]
Quite Frequently it will go to catch a pokemon and then jump to looting a pokestop, and i have enough i items just not Rare Pokemo

**Comment by Roxazlp** [comment]
currently there are 2 options: 
GPX-Pathing -> checking snipeable pokemon after x-set time.
Normal-Pathing -> checking snipeable pokemon after every pokestop.

**Comment by Ilses** [comment]
Hey @Gardagger -- This has to be resolved in the bot client, so you'll need to migrate over to their issue tracker.
