### ISSUE TITLE
Pokesnipers Disabled - #Issue

### ISSUE THREAD

**Issue by am3yar0ra** [5andr0/PogoLocationFeeder#74]
![image](https://cloud.githubusercontent.com/assets/1933816/17318580/e5439a84-58a4-11e6-96de-15d6abfcf703.png)

Pokesnipers from the setting is disabled still the error pops up.

**Comment by incizzle** [comment]
same its weird

**Comment by Ilses** [comment]
ah, we caught that one -- will be fixed in the next release

**Comment by 750z** [comment]
how long till the next release?

**Comment by Ilses** [comment]
Probably quite soon -- master branch is stable and ready, but we're trying to work in one more integration.

**Comment by am3yar0ra** [comment]
I'll surely wait. A small new issue caught.

![image](https://cloud.githubusercontent.com/assets/1933816/17322584/c63f650c-58bb-11e6-88b0-9951956e6b2c.png)

Why is it showing Unknown source and IV 0 ??

**Comment by Ilses** [comment]
I'm closing this since this bug should be fixed in the current v0.1.2. Sorry about that!

@am3yar0ra If you're still having this problem in the latest release, could you open a new issue?
