### ISSUE TITLE
"PokeSnipers API Down: The operation has timed out"

### ISSUE THREAD

**Issue by Squirrel3098** [5andr0/PogoLocationFeeder#75]
Any fixes? or is this a non issue?

**Comment by Hikamii** [comment]
I'm having the same issue. Let me know if you find any fix and vice versa. :)

**Comment by akatimka** [comment]
the same

**Comment by tq01m4m** [comment]
the same

**Comment by sunyipeng418** [comment]
the same

**Comment by akatimka** [comment]
https://github.com/5andr0/PogoLocationFeeder/issues/77

**Comment by Ilses** [comment]
Seems to be fixed in the latest release, so closing for now.
