### ISSUE TITLE
Pokesnipers API down

### ISSUE THREAD

**Issue by Hikamii** [5andr0/PogoLocationFeeder#77]
![387c0c0ee7d0a0eea033a3409093b976](https://cloud.githubusercontent.com/assets/20787868/17318672/05dda324-5856-11e6-911b-aa372377f502.png)

Does anyone know how to fix this issue?

**Comment by akatimka** [comment]
same issue

**Comment by incizzle** [comment]
same issue

**Comment by tq01m4m** [comment]
same issue

**Comment by 750z** [comment]
whats a possible fix?

**Comment by Naldra** [comment]
it is fixed in the Master, you can download it and run when u have visualstudio or wait for new release

**Comment by Naldra** [comment]
![fixed](https://cloud.githubusercontent.com/assets/20788358/17319395/9ab8492c-588d-11e6-8909-218185d6d63b.jpg)

**Comment by tq01m4m** [comment]
Thx,it works now.

**Comment by mhui1125** [comment]
what does "Master" means?

**Comment by djbie** [comment]
@Naldra can you give me new release from master?

**Comment by PackuMan** [comment]
@Naldra when you add new release for this bug? i don't have visual studio to run the source code.. :(

**Comment by Ilses** [comment]
New release should be up pretty soon -- probably no more than a couple of hours.

**Comment by mLgz0rn** [comment]
Why is it that it's crying about the api being down?
Is it just an issue in the current release?
Because the api is clearly not down :p

**Comment by DerekCL** [comment]
same issue with version 0.1.1

**Comment by Sylencer90** [comment]
Yep same issue with hotfix version :/

**Comment by robertosartori** [comment]
I can confirm, it is fixed on master brach. Just wait for the update (or use visual studio).

**Comment by harsh1412** [comment]
Pliss update... :(

**Comment by Sylencer90** [comment]
Just uninstalled visual studio 2 days ago -.- fuck me.

**Comment by itsjustbilly** [comment]
can someone compile this?

**Comment by qwe900** [comment]
https://drive.google.com/open?id=0B_sn0IbirxIUbFJydDE5Mm9pTmc

**Comment by moredhel92** [comment]
ty it works fine now

**Comment by Sylencer90** [comment]
Works fine but my bot keeps scanning for pokemon at the locations in the config file from necrobot, and occasonally uses the data from pokefeeder.

  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinDelayBetweenSnipes": 45000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": true,

is that the correct config?

**Comment by Undertrey** [comment]
Mine:
  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,

Good for me.

**Comment by qwe900** [comment]
just delete the lsit.


Am 02.08.2016 um 15:08 schrieb Sylencer90:

**Comment by itsjustbilly** [comment]
thanks for the compile :)

**Comment by qwe900** [comment]
was just rightlick build, np :D

**Comment by BuggeDKarma** [comment]
https://github.com/dgateles/PogoLocationFeeder

**Comment by Ilses** [comment]
This seems to be fixed in latest release, so I'm closing the issue.
