### ISSUE TITLE
[BUG] random I/O errors

### ISSUE THREAD

**Issue by IsBoris** [5andr0/PogoLocationFeeder#78]
`[08:14:49][WARN] Exception:
System.NotSupportedException: Strumień nie obsługuje równoczesnych operacji odczytu lub zapisu we/wy. <TRANSLATION: Stream does not support simultaneous read/write operation of input/output>
   in System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   in PogoLocationFeeder.Program.<>c__DisplayClass14_0.<<pollDiscordFeed>b__0>d.MoveNext() in C:\Users\anonymous\Downloads\_Apps\Pokemon\PogoLocationFeeder\PogoLocationFeeder\Program.cs:row 204`

**Comment by Ilses** [comment]
Ah, we had a stream.Read in there instead of a stream.ReadAsync
Should be fixed next release

**Comment by 750z** [comment]
how long until the next release?

**Comment by IsBoris** [comment]
I believe that it has been fixed already. Give +1 to confirm, so I can close the issue.

**Comment by Ilses** [comment]
This should be fixed in the current release, so I'll close it for you ;)
