### ISSUE TITLE
log4net: Warn exception while rendering format

### ISSUE THREAD

**Issue by navidemad** [5andr0/PogoLocationFeeder#81]
![format](https://cloud.githubusercontent.com/assets/6686865/17320397/360a6720-5848-11e6-9e18-0d9b3666eb42.png)

**Comment by Ilses** [comment]
Hey -- I believe log4net dependencies were fixed in 0.1.3. Could you try the latest v0.1.4 release, and re-open if this is still an issue?

Thanks!
