### ISSUE TITLE
Stops receiving Pokemon when run for sustained periods of time

### ISSUE THREAD

**Issue by justync7** [5andr0/PogoLocationFeeder#84]
It seems if you run this for more than 15~ minutes it stops receiving Pokemon altogether.

**Comment by solenrus** [comment]
can confirm, but not 15min, longer in my case, but still happens

**Comment by Krayzieeee** [comment]
Yes same here about few hours i think

**Comment by vdepagter** [comment]
Confirmed. But duplicates! #174 #135 #94 #87 #84

**Comment by Ilses** [comment]
Hey -- I believe this should be fixed by the new thread manager in the 0.1.4 release. Could you give that a try, and re-open this if the issue persists?

Thanks!
