### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by s4ndman85** [5andr0/PogoLocationFeeder#86]
hi there
after i've donwloaded the last version and after the first use and the creation the only things i see wrote in the file config.json are:

{
  "Port": 16969,
  "usePokeSnipers": false
}

so compared to previous version it's missing all the part about discord server, can someone give me the code to add please!

thank you

**Comment by mLgz0rn** [comment]
> We have been contacted by Discord regarding server load issues. They will be blocking old bot accounts, and new feed requests have been migrated to a centralized server to allow for better traffic control. We will be opening up donations toward hosting a dedicated server, aimed at providing correct feed outputs for pokemon moves, IVs, and expiration dates.

**Comment by UgaBugaBoo** [comment]
Well we need to know how to filter results from http://pogo-feed.mmoex.com/messages

**Comment by elliottfeng** [comment]
But why my bot dont snipe?

**Comment by s4ndman85** [comment]
so are u telling me i don't have to change anything it the config.json and right now it's not working for server problem not configuration problem?

**Comment by mLgz0rn** [comment]
Yes exactly :) Just wait for it to be updated to the new version, there should be included some fixes there.

**Comment by Ilses** [comment]
@UgaBugaBoo We've added the ability to ignore servers by removing them from discord_channels.json in the latest 0.1.4 release. 

As for the others, if you are having problems, please open a separate issue. I'm closing this since it isn't exactly an issue...

Thanks!
