### ISSUE TITLE
Pings stop after prolonged usage?

### ISSUE THREAD

**Issue by StevePavlin** [5andr0/PogoLocationFeeder#87]
After the program is running for some time (2+ hours), I no longer see any updates from discord channels, is this normal?

**Comment by Rabelaiss** [comment]
Same here, a simple solution could be a bat file that restart pogolocationfeeder every xx minutes

**Comment by vdepagter** [comment]
Confirmed. But duplicates! #174 #135 #94 #87 #84

**Comment by Ilses** [comment]
Hey -- I believe this should be fixed by the new thread manager in the 0.1.4 release. Could you give that a try, and re-open this if the issue persists?

Thanks!
