### ISSUE TITLE
No output, no error

### ISSUE THREAD

**Issue by diksm8** [5andr0/PogoLocationFeeder#9]
I've read the source and as far as I can understand it is supposed to print out the channel, id, lat, lng, and iv of the Pokémon it sends to the bot.

The problem is that mine doesn't print anything and the bot never says anything about sniping.
The only output from the feeder is "Listening... New connection from 127.0.0.1:63969" but nothing happens. It doesn't print out anything else, no errors, no nothing.
I am using the latest feeder and the latest bot built from source. When I close  the feeder I get an error about connection closed by remote host in necro so I know that it's making a connection.

Sorry for my shitty report.

**Comment by sliverfishes** [comment]
Same problem for me with the release binary. I'm using a key to connect.

**Comment by 5andr0** [comment]
you have to use username + pwd. tokens are invite only from mods

**Comment by diksm8** [comment]
I am using email + password.

**Comment by sliverfishes** [comment]
Alright, thanks. I was having trouble with the user/pass always giving errors before but now it works fine. :)

**Comment by skupfer** [comment]
Can you confirm your config looks like this (remove all channels you DONT have access to on your account)

```
{
  "ServerChannels": [
    "90plus_ivonly",
    "high_iv_pokemon",
    "rare_pokemon",
    "coords_bot",
    "rare_spottings",
    "other_pokemon",
    "location",
    "request_pokemon",
    "locationsandroutes",
    "rare_finds",
    "85plus_iv"
  ],
  "DiscordToken": "",
  "Port": 16969,
  "useToken": false,
  "DiscordUser": "your@e.mail",
  "DiscordPassword": "suP3Rs3cr37p455"
}
```

**Comment by diksm8** [comment]
I am using http://pastebin.com/BnqvVR4g and the default feeder config but with my login credentials added.

**Comment by 5andr0** [comment]
@skupfer mind sharing the discord servers where you read from? sounds interesting

**Comment by diksm8** [comment]
Fixed with the latest release.

**Comment by Ilses** [comment]
@diksm8 Could you check your firewall settings and post back?

(@skupfer ditto ^, I'd like to get in on those servers)

**Comment by skupfer** [comment]
Check your whispers on discord. If the invitation doesn't work anymore, let me know.

**Comment by diksm8** [comment]
I have allowed the program in my firewall. It is able to get locations from http://pokesnipers.com/

**Comment by skupfer** [comment]
Please Show your Feeder config !necro

**Comment by diksm8** [comment]
`{
  "ServerChannels": [
    "sniping",
    "high_iv_pokemon",
    "rare_pokemon"
  ],
  "DiscordToken": "",
  "Port": 16969,
  "useToken": false,
  "DiscordUser": "email@com.net",
  "DiscordPassword": "Password",
  "usePokeSnipers": true
}`

**Comment by skupfer** [comment]
Seems fine. And I have to ask you the following: Are you, by 100... no, 1000 percent sure the user you are using has access to these discord chans?

**Comment by diksm8** [comment]
I am on that account now and I am receiving and sending messages just fine.

**Comment by Ilses** [comment]
Cool -- sounds like things are working, so I'm going to close this issue.
