### ISSUE TITLE
pogolocationfeeders servers feed is poor?

### ISSUE THREAD

**Issue by darkholyboy** [5andr0/PogoLocationFeeder#90]
What if we have an option to use our own discord accounts like we had before? Or maybe if you add some channels to the feeder perhaps make it switchable? I know, it's up to you, not demanding anything, just a suggestion.
Actually im only getting locations from:
rare_pokemon_only
coords_only
90iv_room
And i'm using the lasted source

**Comment by skupfer** [comment]
https://github.com/5andr0/PogoLocationFeeder/issues/65

Duplicate. This option would be great, yes. Always better if you have an alternative instead of relying on an external party :-)

**Comment by darkholyboy** [comment]
sorry man, didnt see it xD

**Comment by darkholyboy** [comment]
also we could get some kind of integration with this:
http://spawns.mazbron.net/

**Comment by skupfer** [comment]
Spoke with Ilses, it seems we won't see it back, they have no intention to do so. Use an older release or source pre https://github.com/5andr0/PogoLocationFeeder/commit/c2177d48e83082726aaeee42e600e4f16256720a I think and stick to it. But you could try to modify it yourself, too

**Comment by Ilses** [comment]
Hey -- we were contacted by Discord staff about setting their servers on fire. They have worked with us to set up a dedicated feed which should help with the bandwidth problems. To that end, please migrate to the newest release if possible. We just pushed v0.1.2, which should address a lot of the speed issues of 0.1.1 (and offers a slick GUI, if you're into that),

@darkholyboy Could you post your integration comment in a separate issue with the header [Feature Request] ?
