### ISSUE TITLE
PokeSnipers API down

### ISSUE THREAD

**Issue by Zerotask** [5andr0/PogoLocationFeeder#92]
I get tons of these messages and it doesn't ouput Pokemon of the other channels. So it isn't working at the moment.

**Comment by Gurkengewuerz** [comment]
I think it is the cloudflare (d)DOS protection...

**Comment by CptJackieSparrow** [comment]
i'm having the exact problem too.
still couldn't solve it.
anything i can do?

**Comment by chirick86** [comment]
Same problem

**Comment by Gurkengewuerz** [comment]
compile from source or wait for a new release, there is the problem fixed

**Comment by blackwat3r** [comment]
part of the problem is that its trying to connect to pokesnipers even if you have that set to false in the config

**Comment by Ilses** [comment]
We'd fixed the connection error when pokesniper integration setting is disabled in the current release. I think @Gurkengewuerz is correct in that the new Cloudflare DDoS protection is breaking our integration, so we'll be looking into that for the next release.
