### ISSUE TITLE
Unable to snipe a pokemon?

### ISSUE THREAD

**Issue by tmOreo** [5andr0/PogoLocationFeeder#93]
![screenshot_2](https://cloud.githubusercontent.com/assets/20796048/17330560/2a4064d6-58bf-11e6-92a8-d9645acd74af.jpg)

I have a problem, as exampled in the screenshot with dragonite.. It starts sniping it.. but never actually does snipe it.. is there a fix for this or something.. any help appreciated.

Edit: I have noticed that this is not 100% of the time, as some of the pokemon found.. do actually get sniped.

**Comment by isolah123** [comment]
i guess the spawn time of that pokemon ended, but no information

**Comment by jinkawasaki333** [comment]
@tmOreo It means that the coordinate is fake. That is why the API is not working properly right now because the creator is trying to fight the fakers.

**Comment by tmOreo** [comment]
Oh, so its just someone trolling with fake co-ords.. meaning that there isn't actually a pokemon there to snipe?

**Comment by isolah123** [comment]
@jinkawasaki333 yes and maybe its fake coords

**Comment by tmOreo** [comment]
Well, thanks for the help guys.. I was getting frustrated seeing dragonites, charizards and such.. but not actually being able to snipe them, you've stopped a great deal of anger :D
