### ISSUE TITLE
Stops after 30ish mins?

### ISSUE THREAD

**Issue by 750z** [5andr0/PogoLocationFeeder#94]
So i got the code and im running it in VS, but it stops finding pokemon after 30mins? you have to end up restarting the whole thing?

**Comment by bowie24** [comment]
I'm having this as well

**Comment by djdookie** [comment]
me too. really annoying.

**Comment by vdepagter** [comment]
Confirmed!

**Comment by Ilses** [comment]
I'll test and see if I can reproduce this

**Comment by Ilses** [comment]
Latest master has been going strong for 50 min. Can any of you reproduce as of c8080b ?

**Comment by bowie24** [comment]
Looking through the log, this one has been going strong for a little over 2 hours so some commit has fixed it :)

**Comment by Ilses** [comment]
Thanks for checking! 

@750z try building master for now. We're also trying to pushing another release within a few hours.

**Comment by redline187** [comment]
i have this issue to maybe it should send null packets to discord server to keep connection alive?

**Comment by vdepagter** [comment]
Confirmed. But duplicates! #174 #135 #94 #87 #84

**Comment by Ilses** [comment]
I couldn't ever seem to reproduce this -- have any of you encountered this behavior on the latest release (v1.3.0?)

**Comment by djdookie** [comment]
No. Seems to work fine now. But Bot is not working anymore due to API changes of niantic. :(

**Comment by Ilses** [comment]
Hey -- I believe this should be fixed by the new thread manager in the 0.1.4 release. Could you give that a try, and re-open this if the issue persists?

Thanks!
